# See https://www.gitpod.io/docs/config-gitpod-file
tasks:
  - name: Development
    init: npm install && gp sync-done install
    command: npm run dev

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - biomejs.biome
    - EditorConfig.EditorConfig
    - bradlc.vscode-tailwindcss
