comment: false

github_checks:
  annotations: false

codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
