packages:
  - packages/*
  - templates/*
  - nextjs
  - examples
  - guide
  - website
  - app

allowBuilds:
  "@clerk/shared": false
  core-js: false
  esbuild: true
  msw: false
  sharp: true
  workerd: true

overrides:
  "@wordpress/components>@ariakit/react": "workspace:*"

patchedDependencies:
  "@changesets/apply-release-plan@7.1.1": "patches/@changesets__apply-release-plan@7.1.1.patch"

publicHoistPattern:
  - "*react*"
  - "*testing-library*"

saveExact: true
