/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e77b9bcfbea90c3c9a1de6ad38219dee)
declare namespace Cloudflare {
  interface PreviewEnv {
    ASSETS: Fetcher;
  }
  interface Env {
    ASSETS: Fetcher;
    SESSION?: KVNamespace;
    PLUS?: KVNamespace;
    EVENTS?: KVNamespace;
    ADMIN?: KVNamespace;
  }
}
interface Env extends Cloudflare.Env {}
