/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6cf8857bd3f653ef6a79dadb68bb7c1a)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./site/dist/server/entry");
  }
  interface PreviewEnv {
    SESSION: KVNamespace;
    PLUS: KVNamespace;
    EVENTS: KVNamespace;
    ADMIN: KVNamespace;
    ASSETS: Fetcher;
  }
  interface Env {
    SESSION: KVNamespace;
    PLUS: KVNamespace;
    EVENTS: KVNamespace;
    ADMIN: KVNamespace;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
