/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c6bb3163304ead9b8c90a63324d945c0)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./site/dist/_worker.js/index");
	}
	interface PreviewEnv {
		ASSETS: Fetcher;
	}
	interface Env {
		ASSETS: Fetcher;
		SESSION?: KVNamespace;
		PLUS?: KVNamespace;
		EVENTS?: KVNamespace;
		ADMIN?: KVNamespace;
	}
}
interface Env extends Cloudflare.Env {}
