name: setup
description: Set up environment

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
      with:
        cache: ${{ runner.os != 'macOS' }}

    - name: Set up Node
      uses: actions/setup-node@v7
      with:
        node-version-file: package.json

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
