name: setup
description: Set up environment

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      with:
        cache: true

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
