// Long enough that the selected Onion sits well below a short scrollport, so an
// open that never presents it leaves the list parked on Artichoke.
export const vegetables = [
  "Artichoke",
  "Arugula",
  "Asparagus",
  "Beet",
  "Bell pepper",
  "Broccoli",
  "Brussels sprout",
  "Cabbage",
  "Carrot",
  "Cauliflower",
  "Celery",
  "Chard",
  "Collard greens",
  "Corn",
  "Cucumber",
  "Eggplant",
  "Endive",
  "Fennel",
  "Garlic",
  "Green bean",
  "Kale",
  "Leek",
  "Lettuce",
  "Mushroom",
  "Okra",
  "Onion",
  "Parsnip",
  "Pea",
  "Potato",
  "Pumpkin",
  "Radish",
  "Shallot",
  "Spinach",
  "Sweet potato",
  "Tomato",
  "Turnip",
  "Zucchini",
];
