/* eslint-disable */
// Automatically generated by ../../../../scripts/build/utils.js
export default {
  "reakit-system-palette": require("reakit-system-palette"),
  "reakit-system-palette/utils/usePalette": require("reakit-system-palette/utils/usePalette"),
  "reakit-system-palette/utils/p": require("reakit-system-palette/utils/p"),
  "reakit-system-palette/utils": require("reakit-system-palette/utils"),
  "reakit-system-palette/system/useBox": require("reakit-system-palette/system/useBox"),
  "reakit-system-palette/system/palette": require("reakit-system-palette/system/palette"),
  "reakit-system-palette/system": require("reakit-system-palette/system")
};
