/* eslint-disable */
// Automatically generated by ../../../../scripts/build/utils.js
export default {
  "reakit-system": require("reakit-system"),
  "reakit-system/useToken": require("reakit-system/useToken"),
  "reakit-system/useProps": require("reakit-system/useProps"),
  "reakit-system/useOptions": require("reakit-system/useOptions"),
  "reakit-system/useCreateElement": require("reakit-system/useCreateElement"),
  "reakit-system/mergeSystem": require("reakit-system/mergeSystem"),
  "reakit-system/createHook": require("reakit-system/createHook"),
  "reakit-system/createComponent": require("reakit-system/createComponent"),
  "reakit-system/SystemProvider": require("reakit-system/SystemProvider"),
  "reakit-system/SystemContext": require("reakit-system/SystemContext")
};
