/* eslint-disable */
// Automatically generated by ../../../../scripts/build/utils.js
export default {
  "reakit-system-bootstrap": require("reakit-system-bootstrap"),
  "reakit-system-bootstrap/palette": require("reakit-system-bootstrap/palette"),
  "reakit-system-bootstrap/Tooltip": require("reakit-system-bootstrap/Tooltip"),
  "reakit-system-bootstrap/Toolbar": require("reakit-system-bootstrap/Toolbar"),
  "reakit-system-bootstrap/Tabbable": require("reakit-system-bootstrap/Tabbable"),
  "reakit-system-bootstrap/Tab": require("reakit-system-bootstrap/Tab"),
  "reakit-system-bootstrap/Separator": require("reakit-system-bootstrap/Separator"),
  "reakit-system-bootstrap/Popover": require("reakit-system-bootstrap/Popover"),
  "reakit-system-bootstrap/Menu": require("reakit-system-bootstrap/Menu"),
  "reakit-system-bootstrap/Group": require("reakit-system-bootstrap/Group"),
  "reakit-system-bootstrap/Form": require("reakit-system-bootstrap/Form"),
  "reakit-system-bootstrap/Dialog": require("reakit-system-bootstrap/Dialog"),
  "reakit-system-bootstrap/Button": require("reakit-system-bootstrap/Button"),
  "reakit-system-bootstrap/Box": require("reakit-system-bootstrap/Box")
};
