/* eslint-disable */
// Automatically generated by ../../../../scripts/build/utils.js
export default {
  "reakit-system-palette": require("reakit-system-palette"),
  "reakit-system-palette/utils/ref": require("reakit-system-palette/utils/ref"),
  "reakit-system-palette/utils/palette": require("reakit-system-palette/utils/palette"),
  "reakit-system-palette/utils/lighten": require("reakit-system-palette/utils/lighten"),
  "reakit-system-palette/utils/isLight": require("reakit-system-palette/utils/isLight"),
  "reakit-system-palette/utils/isDark": require("reakit-system-palette/utils/isDark"),
  "reakit-system-palette/utils": require("reakit-system-palette/utils"),
  "reakit-system-palette/utils/fade": require("reakit-system-palette/utils/fade"),
  "reakit-system-palette/utils/darken": require("reakit-system-palette/utils/darken"),
  "reakit-system-palette/utils/contrast": require("reakit-system-palette/utils/contrast"),
  "reakit-system-palette/palette": require("reakit-system-palette/palette"),
  "reakit-system-palette/Box": require("reakit-system-palette/Box")
};
