/* eslint-disable */
// Automatically generated by ../../../../scripts/build/utils.js
export default {
  "reakit-playground": require("reakit-playground"),
  "reakit-playground/useEditorState": require("reakit-playground/useEditorState"),
  "reakit-playground/Preview": require("reakit-playground/Preview"),
  "reakit-playground/ErrorMessage": require("reakit-playground/ErrorMessage"),
  "reakit-playground/ErrorBoundary": require("reakit-playground/ErrorBoundary"),
  "reakit-playground/Editor": require("reakit-playground/Editor")
};
