/* eslint-disable */
// Automatically generated by ../../../../scripts/build/utils.js
export default {
  "reakit-test-utils": require("reakit-test-utils"),
  "reakit-test-utils/act": require("reakit-test-utils/act"),
  "reakit-test-utils/blur": require("reakit-test-utils/blur"),
  "reakit-test-utils/click": require("reakit-test-utils/click"),
  "reakit-test-utils/fireEvent": require("reakit-test-utils/fireEvent"),
  "reakit-test-utils/focus": require("reakit-test-utils/focus"),
  "reakit-test-utils/hooks/act": require("reakit-test-utils/hooks/act"),
  "reakit-test-utils/hooks/index": require("reakit-test-utils/hooks/index"),
  "reakit-test-utils/hooks/renderHook": require("reakit-test-utils/hooks/renderHook"),
  "reakit-test-utils/hover": require("reakit-test-utils/hover"),
  "reakit-test-utils/jestSerializerStripFunctions": require("reakit-test-utils/jestSerializerStripFunctions"),
  "reakit-test-utils/mockClientRects": require("reakit-test-utils/mockClientRects"),
  "reakit-test-utils/press": require("reakit-test-utils/press"),
  "reakit-test-utils/render": require("reakit-test-utils/render"),
  "reakit-test-utils/type": require("reakit-test-utils/type"),
  "reakit-test-utils/wait": require("reakit-test-utils/wait")
};
