/* eslint-disable */
// Automatically generated by ../../../../scripts/build/utils.js
export default {
  "reakit-playground": require("reakit-playground"),
  "reakit-playground/usePlaygroundState": require("reakit-playground/usePlaygroundState"),
  "reakit-playground/system": require("reakit-playground/system"),
  "reakit-playground/PlaygroundPreview": require("reakit-playground/PlaygroundPreview"),
  "reakit-playground/PlaygroundEditor": require("reakit-playground/PlaygroundEditor"),
  "reakit-playground/ErrorMessage": require("reakit-playground/ErrorMessage"),
  "reakit-playground/ErrorBoundary": require("reakit-playground/ErrorBoundary")
};
