import { isTextField } from "@ariakit/utils";
import { beforeEach } from "vitest";
import { commands, page, server, userEvent } from "vitest/browser";
import type { Locator } from "vitest/browser";
import { setLastHovered } from "./__hover-state.ts";
import { setInteractionDriver } from "./__interaction-driver.ts";

type Modifier = "Alt" | "Control" | "Meta" | "Shift";

interface PointerOptions {
  button?: "left" | "middle" | "right";
  force?: boolean;
  modifiers?: Modifier[];
  position?: { x: number; y: number };
}

interface ElementTarget {
  locator?: Locator;
  selector: string;
  temporaryAttribute?: string;
}

interface PointerCommand {
  selector: string;
  temporaryAttribute?: string;
  options: PointerOptions;
}

interface PressCommand {
  selector: string;
  temporaryAttribute?: string;
  key: string;
  modifiers: Modifier[];
}

declare module "vitest/browser" {
  interface BrowserCommands {
    ariakitClick(command: PointerCommand): Promise<void>;
    ariakitHover(command: PointerCommand): Promise<void>;
    ariakitPress(command: PressCommand): Promise<void>;
    ariakitTab(shift: boolean, webkit: boolean): Promise<void>;
  }
}

const modifierOptionNames = [
  "altKey",
  "ctrlKey",
  "metaKey",
  "shiftKey",
] as const;
const clickOptionNames = [
  ...modifierOptionNames,
  "button",
  "clientX",
  "clientY",
];
const hoverOptionNames = [...modifierOptionNames, "clientX", "clientY"];
const keyboardOptionNames = [...modifierOptionNames, "repeat"];
const typeOptionNames = [...modifierOptionNames, "isComposing"];
const simulatedPointerDocuments = new WeakSet<Document>();

function useSimulatedPointer(element: Element) {
  simulatedPointerDocuments.add(element.ownerDocument);
  return false;
}

function hasSimulatedPointer(element: Element) {
  return simulatedPointerDocuments.has(element.ownerDocument);
}

function hasUnsupportedOptions(
  options: object | undefined,
  supportedOptions: readonly string[],
) {
  if (!options) return false;
  const prototype = Object.getPrototypeOf(options);
  if (prototype !== null && prototype !== Object.prototype) return true;
  return Object.getOwnPropertyNames(options).some(
    (option) => !supportedOptions.includes(option),
  );
}

function getModifiers(options?: EventModifierInit) {
  const modifiers: Modifier[] = [];
  if (options?.altKey) {
    modifiers.push("Alt");
  }
  if (options?.ctrlKey) {
    modifiers.push("Control");
  }
  if (options?.metaKey) {
    modifiers.push("Meta");
  }
  if (options?.shiftKey) {
    modifiers.push("Shift");
  }
  return modifiers;
}

function getMouseButton(button?: number) {
  if (button === 1) return "middle" as const;
  if (button === 2) return "right" as const;
  return "left" as const;
}

function isSupportedMouseButton(button?: number) {
  return button == null || button === 0 || button === 1 || button === 2;
}

function getClickOptions(options?: PointerEventInit, force = false) {
  if (hasClientPosition(options)) return false;
  const modifiers = getModifiers(options);
  return {
    button: getMouseButton(options?.button),
    force: force || undefined,
    modifiers: modifiers.length ? modifiers : undefined,
  };
}

function isDisabled(element: Element) {
  return element.matches(":disabled");
}

function isCurrentDocument(element: Element) {
  return element.ownerDocument === document;
}

function isAriaDisabled(element: Element) {
  return element.getAttribute("aria-disabled") === "true";
}

function ignoresPointerEvents(element: Element) {
  const window = element.ownerDocument.defaultView;
  return window?.getComputedStyle(element).pointerEvents === "none";
}

function isInShadowRoot(element: Element) {
  const { defaultView } = element.ownerDocument;
  if (!defaultView) return false;
  return element.getRootNode() instanceof defaultView.ShadowRoot;
}

function hasClientPosition(options?: PointerEventInit) {
  if (!options) return;
  return "clientX" in options || "clientY" in options;
}

function getTemporaryAttribute() {
  return `data-ariakit-test-target-${crypto.randomUUID().replaceAll("-", "")}`;
}

async function withElementTarget<T>(
  element: Element,
  callback: (target: ElementTarget) => Promise<T>,
) {
  const locator = page.elementLocator(element);
  try {
    if (locator.query() === element) {
      return await callback({ locator, selector: locator.selector });
    }
  } catch {
    // Vitest 4.1.10 does not escape slashes in the CSS path generated by
    // page.elementLocator(), which breaks portal IDs such as "portal/_r_2_".
    // Fall through to a private selector until Vitest fixes that path.
  }

  const temporaryAttribute = getTemporaryAttribute();
  element.setAttribute(temporaryAttribute, "");
  try {
    return await callback({
      selector: `[${temporaryAttribute}]`,
      temporaryAttribute,
    });
  } finally {
    if (element.getAttribute(temporaryAttribute) === "") {
      element.removeAttribute(temporaryAttribute);
    }
  }
}

async function clickTarget(target: ElementTarget, options: PointerOptions) {
  if (target.locator) {
    return userEvent.click(target.locator, options);
  }
  return commands.ariakitClick({
    selector: target.selector,
    temporaryAttribute: target.temporaryAttribute,
    options,
  });
}

async function hoverTarget(target: ElementTarget, options: PointerOptions) {
  if (target.locator) {
    return userEvent.hover(target.locator, options);
  }
  return commands.ariakitHover({
    selector: target.selector,
    temporaryAttribute: target.temporaryAttribute,
    options,
  });
}

async function click(
  element: Element,
  options?: PointerEventInit,
  tap?: boolean,
) {
  if (!isCurrentDocument(element)) return false;
  if (hasSimulatedPointer(element)) return false;
  if (tap) {
    return useSimulatedPointer(element);
  }
  if (hasUnsupportedOptions(options, clickOptionNames)) {
    return useSimulatedPointer(element);
  }
  if (!isSupportedMouseButton(options?.button)) {
    return useSimulatedPointer(element);
  }
  if (element === element.ownerDocument.body) {
    return useSimulatedPointer(element);
  }
  const { defaultView } = element.ownerDocument;
  if (defaultView && element instanceof defaultView.HTMLOptionElement) {
    return useSimulatedPointer(element);
  }
  const clickOptions = getClickOptions(
    options,
    isDisabled(element) ||
      isAriaDisabled(element) ||
      ignoresPointerEvents(element) ||
      isInShadowRoot(element),
  );
  if (!clickOptions) {
    return useSimulatedPointer(element);
  }
  await withElementTarget(element, (target) =>
    clickTarget(target, clickOptions),
  );
  setLastHovered(element);
  return true;
}

async function rightClick(element: Element, options?: PointerEventInit) {
  if (!isCurrentDocument(element)) return false;
  if (hasSimulatedPointer(element)) return false;
  if (hasUnsupportedOptions(options, clickOptionNames)) {
    return useSimulatedPointer(element);
  }
  if (element === element.ownerDocument.body) {
    return useSimulatedPointer(element);
  }
  const clickOptions = getClickOptions(
    options,
    isDisabled(element) ||
      isAriaDisabled(element) ||
      ignoresPointerEvents(element) ||
      isInShadowRoot(element),
  );
  if (!clickOptions) {
    return useSimulatedPointer(element);
  }
  await withElementTarget(element, (target) =>
    clickTarget(target, {
      ...clickOptions,
      button: "right",
    }),
  );
  setLastHovered(element);
  return true;
}

async function hover(element: Element, options?: PointerEventInit) {
  if (!isCurrentDocument(element)) return false;
  if (hasSimulatedPointer(element)) return false;
  if (hasUnsupportedOptions(options, hoverOptionNames)) {
    return useSimulatedPointer(element);
  }
  if (hasClientPosition(options)) {
    return useSimulatedPointer(element);
  }
  if (element === element.ownerDocument.body) {
    const rect = element.getBoundingClientRect();
    await withElementTarget(element, (target) =>
      hoverTarget(target, {
        force: true,
        position: {
          x: Math.max(0, rect.width - 1),
          y: Math.max(0, rect.height - 1),
        },
      }),
    );
    setLastHovered(element);
    return true;
  }
  const modifiers = getModifiers(options);
  await withElementTarget(element, (target) =>
    hoverTarget(target, {
      force: ignoresPointerEvents(element) || undefined,
      modifiers: modifiers.length ? modifiers : undefined,
    }),
  );
  setLastHovered(element);
  return true;
}

function getKeyToken(key: string, action?: "down" | "up") {
  const name = key === " " ? "Space" : key;
  if (action === "down") {
    return `{${name}>}`;
  }
  if (action === "up") {
    return `{/${name}}`;
  }
  if (key.length > 1 || key === " ") {
    return `{${name}}`;
  }
  if (key === "{") return "{{";
  if (key === "[") return "[[";
  return key;
}

function getModifierTokens(options: KeyboardEventInit, action: "down" | "up") {
  const modifiers = getModifiers(options);
  if (action === "up") {
    modifiers.reverse();
  }
  return modifiers.map((modifier) => getKeyToken(modifier, action)).join("");
}

function getPressKey(key: string) {
  return key === " " ? "Space" : key;
}

async function press(
  key: string,
  element: Element,
  options: KeyboardEventInit = {},
) {
  if (!isCurrentDocument(element)) return false;
  if (hasUnsupportedOptions(options, keyboardOptionNames)) {
    return false;
  }
  if (options.repeat) return false;
  if (key === "Backspace" && !isTextField(element)) return false;
  const down = getModifierTokens(options, "down");
  const up = getModifierTokens(options, "up");
  const sequence = `${down}${getKeyToken(key)}${up}`;
  if (key === "Tab") {
    if (options.altKey) return false;
    if (options.ctrlKey) return false;
    if (options.metaKey) return false;
    await commands.ariakitTab(!!options.shiftKey, server.browser === "webkit");
    return true;
  }
  if (element === element.ownerDocument.body) {
    await userEvent.keyboard(sequence);
  } else {
    await withElementTarget(element, (target) =>
      commands.ariakitPress({
        selector: target.selector,
        temporaryAttribute: target.temporaryAttribute,
        key: getPressKey(key),
        modifiers: getModifiers(options),
      }),
    );
  }
  return true;
}

function getTypeText(text: string) {
  let result = "";
  for (const character of text) {
    if (character === "\b") {
      result += "{Backspace}";
    } else if (character === "\x7f") {
      result += "{Delete}";
    } else if (character === "\n") {
      result += "{Enter}";
    } else if (character === "\t") {
      result += "{Tab}";
    } else {
      result += getKeyToken(character);
    }
  }
  return result;
}

function getTypeKey(character: string) {
  if (character === "\b") return "Backspace";
  if (character === "\x7f") return "Delete";
  if (character === "\n") return "Enter";
  if (character === "\t") return "Tab";
  return character;
}

async function type(
  text: string,
  element: HTMLElement,
  options: InputEventInit | KeyboardEventInit = {},
) {
  if (!isCurrentDocument(element)) return false;
  if (hasUnsupportedOptions(options, typeOptionNames)) {
    return false;
  }
  if ("isComposing" in options && options.isComposing) return false;
  if (getModifiers(options).length) return false;
  let target = element;
  for (const character of text) {
    await withElementTarget(target, async (elementTarget) => {
      if (isTextField(target) && elementTarget.locator) {
        await userEvent.type(elementTarget.locator, getTypeText(character), {
          skipClick: true,
        });
      } else {
        await commands.ariakitPress({
          selector: elementTarget.selector,
          temporaryAttribute: elementTarget.temporaryAttribute,
          key: getTypeKey(character),
          modifiers: [],
        });
      }
    });
    await new Promise<void>((resolve) => {
      requestAnimationFrame(() => resolve());
    });
    const activeElement = target.ownerDocument.activeElement;
    if (
      activeElement instanceof HTMLElement &&
      activeElement !== document.body
    ) {
      target = activeElement;
    }
  }
  return true;
}

if (server.provider === "playwright") {
  setInteractionDriver({ click, hover, press, rightClick, type });
  beforeEach(() => {
    simulatedPointerDocuments.delete(document);
  });
}
