// Automatically generated by scripts/build/keys.js
const PLAYGROUND_STATE_KEYS = ["code", "update"] as const;
export const ERROR_MESSAGE_KEYS = [...PLAYGROUND_STATE_KEYS, "error"] as const;
export const PLAYGROUND_EDITOR_KEYS = [
  ...PLAYGROUND_STATE_KEYS,
  "mode",
  "theme",
  "readOnly",
  "tabSize",
  "lineWrapping",
  "autoRefresh",
  "maxHeight",
] as const;
export const PLAYGROUND_PREVIEW_KEYS = [
  ...PLAYGROUND_STATE_KEYS,
  "unstyled",
  "modules",
  "componentName",
] as const;
