name: 🚀 Feature request
description: Suggest an idea for this project.
labels: ["feature"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Motivation
      description: Outline the motivation for the proposal.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Usage example
      description: Provide code examples for how this feature could be used.
      placeholder: |
        As string:
        ```jsx
        <NewComponent newProp="newValue" />
        ```

        As boolean:
        ```jsx
        <NewComponent newProp />
        ```
  - type: textarea
    validations:
      required: true
    attributes:
      label: Requirements
      description: List the feature requirements. This will help us [write tests](https://github.com/ariakit/ariakit/blob/main/contributing.md#testing-the-example).
      placeholder: |
        - The component should open when pressing the A key.
        - The component should close when pressing the B key.
        - The component shouldn't close when `newProp` is set to `true`.
  - type: textarea
    attributes:
      label: Workaround
      description: If you have implemented this feature in userland, please describe your solution here to help others. 
  - type: textarea
    attributes:
      label: Possible implementations
      description: If possible, describe how this feature could be implemented in the library code.
