export const fonts = [
  "Roboto",
  "Open Sans",
  "Noto Sans JP",
  "Montserrat",
  "Poppins",
  "Lato",
  "Inter",
  "Material Icons",
  "Roboto Condensed",
  "Roboto Mono",
  "Oswald",
  "Noto Sans",
  "Raleway",
  "Nunito",
  "Nunito Sans",
  "Playfair Display",
  "Ubuntu",
  "Rubik",
  "Noto Sans KR",
  "Merriweather",
  "Roboto Slab",
  "PT Sans",
  "Kanit",
  "Work Sans",
  "Lora",
  "DM Sans",
  "Quicksand",
  "Noto Sans TC",
  "Mulish",
  "Fira Sans",
  "Barlow",
  "Inconsolata",
  "Manrope",
  "Material Symbols Outlined",
  "IBM Plex Sans",
  "Material Icons Outlined",
  "PT Serif",
  "Titillium Web",
  "Josefin Sans",
  "Heebo",
  "Noto Serif",
  "Karla",
  "Nanum Gothic",
  "Bebas Neue",
  "Noto Color Emoji",
  "Libre Franklin",
  "Material Symbols Rounded",
  "Outfit",
  "Hind Siliguri",
  "Mukta",
  "Libre Baskerville",
  "Source Code Pro",
  "Jost",
  "EB Garamond",
  "Space Grotesk",
  "Dancing Script",
  "Arimo",
  "Fira Sans Condensed",
  "Archivo",
  "Dosis",
  "Cabin",
  "Anton",
  "Noto Sans SC",
  "Bitter",
  "Barlow Condensed",
  "PT Sans Narrow",
  "Figtree",
  "Source Sans 3",
  "Crimson Text",
  "Noto Serif JP",
  "Abel",
  "Hind",
  "Teko",
  "Material Icons Round",
  "Cairo",
  "Exo 2",
  "Oxygen",
  "Overpass",
  "Plus Jakarta Sans",
  "Public Sans",
  "Assistant",
  "Varela Round",
  "Prompt",
  "Pacifico",
  "Red Hat Display",
  "Signika Negative",
  "Material Icons Sharp",
  "Arvo",
  "Lexend",
  "M PLUS Rounded 1c",
  "Comfortaa",
  "Fjalla One",
  "IBM Plex Mono",
  "Lobster",
  "Caveat",
  "Schibsted Grotesk",
  "Chakra Petch",
  "Maven Pro",
  "Cormorant Garamond",
  "Lilita One",
  "Archivo Black",
  "Rajdhani",
  "Noto Sans Arabic",
  "Material Icons Two Tone",
  "Sora",
  "Asap",
  "Slabo 27px",
  "Noto Sans HK",
  "Zilla Slab",
  "Shadows Into Light",
  "Barlow Semi Condensed",
  "Satisfy",
  "Roboto Flex",
  "Nanum Myeongjo",
  "Nanum Gothic Coding",
  "Tajawal",
  "Permanent Marker",
  "Abril Fatface",
  "Saira Condensed",
  "IBM Plex Sans Arabic",
  "Merriweather Sans",
  "DM Serif Display",
  "Almarai",
  "Rowdies",
  "Inter Tight",
  "Play",
  "IBM Plex Serif",
  "Questrial",
  "Indie Flower",
  "Urbanist",
  "Domine",
  "Asap Condensed",
  "M PLUS 1p",
  "Alegreya",
  "Source Serif 4",
  "Cinzel",
  "Signika",
  "Catamaran",
  "Spicy Rice",
  "Vollkorn",
  "Archivo Narrow",
  "Noto Sans Thai",
  "Oxanium",
  "Exo",
  "Cormorant",
  "Noto Kufi Arabic",
  "Frank Ruhl Libre",
  "Bree Serif",
  "Marcellus",
  "Changa",
  "Acme",
  "Mate",
  "Great Vibes",
  "Hind Madurai",
  "Sarabun",
  "Amatic SC",
  "Be Vietnam Pro",
  "Orbitron",
  "Montserrat Alternates",
  "Tinos",
  "ABeeZee",
  "Lexend Deca",
  "Passion One",
  "Yanone Kaffeesatz",
  "Righteous",
  "Concert One",
  "Spectral",
  "Noto Sans Display",
  "Alfa Slab One",
  "Albert Sans",
  "League Spartan",
  "Rubik Mono One",
  "Prata",
  "Alegreya Sans",
  "Kalam",
  "Chivo",
  "Saira",
  "Patua One",
  "Encode Sans",
  "Amiri",
  "Antic Slab",
  "Noto Serif KR",
  "Roboto Serif",
  "Oleo Script",
  "Gothic A1",
  "PT Sans Caption",
  "Noto Sans Bengali",
  "Noto Serif TC",
  "Cardo",
  "Mate SC",
  "Courgette",
  "Rokkitt",
  "Pirata One",
  "Merienda",
  "Bowlby One",
  "Squada One",
  "Ubuntu Mono",
  "Readex Pro",
  "Martel",
  "Crimson Pro",
  "Itim",
  "Cantarell",
  "Crete Round",
  "Didact Gothic",
  "Sawarabi Mincho",
  "Titan One",
  "Alata",
  "Luckiest Guy",
  "Zen Kaku Gothic New",
  "Lobster Two",
  "Gloria Hallelujah",
  "Bodoni Moda",
  "JetBrains Mono",
  "Kaushan Script",
  "Atkinson Hyperlegible",
  "Ubuntu Condensed",
  "Space Mono",
  "Eczar",
  "Creepster",
  "Yatra One",
  "Francois One",
  "Baloo Paaji 2",
  "Inria Sans",
  "Russo One",
  "Paytone One",
  "Sacramento",
  "Noticia Text",
  "Yellowtail",
  "Yantramanav",
  "Libre Caslon Text",
  "Philosopher",
  "Bangers",
  "DM Serif Text",
  "Neucha",
  "Old Standard TT",
  "Silkscreen",
  "Quattrocento",
  "Sawarabi Gothic",
  "Yeseva One",
  "Sanchez",
  "Neuton",
  "Encode Sans Condensed",
  "Courier Prime",
  "Libre Barcode 39",
  "Bungee",
  "Josefin Slab",
  "Zeyada",
  "Sofia",
  "Poiret One",
  "Cookie",
  "Khand",
  "Quattrocento Sans",
  "Allura",
  "Sen",
  "Red Hat Text",
  "Tenor Sans",
  "Commissioner",
  "Zen Maru Gothic",
  "Gruppo",
  "Unna",
  "Patrick Hand",
  "Gilda Display",
  "Comic Neue",
  "Taviraj",
  "IBM Plex Sans Condensed",
  "Staatliches",
  "Pathway Gothic One",
  "Gelasio",
  "Rubik Bubbles",
  "Macondo",
  "Architects Daughter",
  "Literata",
  "Tangerine",
  "Fraunces",
  "Special Elite",
  "Syne",
  "Kumbh Sans",
  "Advent Pro",
  "Krub",
  "Baskervville",
  "News Cycle",
  "Noto Sans Mono",
  "Fugaz One",
  "Geologica",
  "Aleo",
  "Faustina",
  "El Messiri",
  "Noto Naskh Arabic",
  "Cuprum",
  "STIX Two Text",
  "DM Mono",
  "Onest",
  "Hanken Grotesk",
  "Jura",
  "Parisienne",
  "Epilogue",
  "Playfair Display SC",
  "Kosugi Maru",
  "Noto Sans Tamil",
  "Dela Gothic One",
  "Baloo 2",
  "Mitr",
  "Vidaloka",
  "PT Mono",
  "Nerko One",
  "Material Symbols Sharp",
  "Unbounded",
  "Sriracha",
  "Baloo Bhaijaan 2",
  "Shippori Mincho",
  "Saira Semi Condensed",
  "Audiowide",
  "Mukta Malar",
  "Sofia Sans",
  "Alice",
  "Noto Serif Bengali",
  "Fira Sans Extra Condensed",
  "Sofia Sans Condensed",
  "Homemade Apple",
  "Pridi",
  "Fredoka",
  "Amaranth",
  "Lalezar",
  "Niramit",
  "Reenie Beanie",
  "Ropa Sans",
  "Alex Brush",
  "Nothing You Could Do",
  "Volkhov",
  "Sorts Mill Goudy",
  "Arsenal",
  "Ultra",
  "Aclonica",
  "Handlee",
  "Blinker",
  "Hammersmith One",
  "Andika",
  "VT323",
  "Hind Vadodara",
  "Instrument Sans",
  "Press Start 2P",
  "Radio Canada",
  "Abhaya Libre",
  "Forum",
  "Bricolage Grotesque",
  "BIZ UDPGothic",
  "Bad Script",
  "Istok Web",
  "Bai Jamjuree",
  "Playball",
  "Cousine",
  "Mandali",
  "Mr Dafoe",
  "Fira Mono",
  "Antonio",
  "Changa One",
  "Unica One",
  "Alegreya Sans SC",
  "Alexandria",
  "League Gothic",
  "Playfair",
  "Rammetto One",
  "Noto Sans Malayalam",
  "Monda",
  "Ruda",
  "Varela",
  "Monoton",
  "Gudea",
  "Nanum Pen Script",
  "Wix Madefor Text",
  "Viga",
  "Carter One",
  "Mada",
  "Lusitana",
  "Fira Code",
  "Rock Salt",
  "Anuphan",
  "Noto Serif SC",
  "Damion",
  "Secular One",
  "Share Tech Mono",
  "Economica",
  "Londrina Solid",
  "Quantico",
  "Black Ops One",
  "Newsreader",
  "Petrona",
  "Cabin Condensed",
  "Martel Sans",
  "Anonymous Pro",
  "Pangolin",
  "Marck Script",
  "Julius Sans One",
  "Reem Kufi",
  "Ramabhadra",
  "Pinyon Script",
  "Six Caps",
  "Libre Bodoni",
  "Vazirmatn",
  "Zen Old Mincho",
  "Caveat Brush",
  "Basic",
  "Actor",
  "Cormorant Infant",
  "Sarala",
  "Rufina",
  "Pragati Narrow",
  "Allison",
  "Averia Serif Libre",
  "Covered By Your Grace",
  "Big Shoulders Display",
  "Pontano Sans",
  "Grandstander",
  "BenchNine",
  "Italianno",
  "Electrolize",
  "Balsamiq Sans",
  "GFS Didot",
  "Khula",
  "Syncopate",
  "Gowun Batang",
  "Amita",
  "Karma",
  "Gochi Hand",
  "Calistoga",
  "Noto Sans Devanagari",
  "Black Han Sans",
  "Oranienbaum",
  "Days One",
  "Golos Text",
  "Holtwood One SC",
  "Adamina",
  "Leckerli One",
  "Noto Nastaliq Urdu",
  "Hind Guntur",
  "Mrs Saint Delafield",
  "Sansita",
  "Georama",
  "Noto Sans Hebrew",
  "Cinzel Decorative",
  "Alef",
  "Judson",
  "Kameron",
  "Yrsa",
  "Shrikhand",
  "Kiwi Maru",
  "Berkshire Swash",
  "Delius",
  "Noto Serif Display",
  "Sintony",
  "Palanquin Dark",
  "Racing Sans One",
  "Arapey",
  "Corben",
  "IBM Plex Sans Thai",
  "Cabin Sketch",
  "Bungee Shade",
  "Besley",
  "Italiana",
  "Gupter",
  "Athiti",
  "Darker Grotesque",
  "La Belle Aurore",
  "Charm",
  "Chewy",
  "Brygada 1918",
  "Coda",
  "Shippori Mincho B1",
  "Glegoo",
  "Laila",
  "Saira Extra Condensed",
  "Palanquin",
  "Herr Von Muellerhoff",
  "Kreon",
  "Telex",
  "Jua",
  "Boogaloo",
  "Belleza",
  "Marcellus SC",
  "M PLUS 1",
  "Bevan",
  "Michroma",
  "Lemonada",
  "Armata",
  "Just Another Hand",
  "Julee",
  "Cedarville Cursive",
  "Do Hyeon",
  "Alatsi",
  "Seaweed Script",
  "Candal",
  "Fredericka the Great",
  "Mali",
  "Nobile",
  "Akshar",
  "Nanum Brush Script",
  "Shadows Into Light Two",
  "Halant",
  "Tomorrow",
  "Rye",
  "BioRhyme",
  "Alumni Sans",
  "PT Serif Caption",
  "Gabarito",
  "Livvic",
  "Allerta Stencil",
  "Aldrich",
  "Gantari",
  "Jaldi",
  "Lustria",
  "Krona One",
  "Norican",
  "Graduate",
  "Antic",
  "Share",
  "MuseoModerno",
  "Gravitas One",
  "Averia Libre",
  "Ibarra Real Nova",
  "Suez One",
  "Podkova",
  "Cantata One",
  "Nixie One",
  "Caudex",
  "Cutive Mono",
  "Zen Kaku Gothic Antique",
  "Rozha One",
  "Rancho",
  "Overpass Mono",
  "K2D",
  "Libre Barcode 39 Text",
  "Prociono",
  "BIZ UDGothic",
  "Spinnaker",
  "Coming Soon",
  "Sofia Sans Extra Condensed",
  "Anek Malayalam",
  "Padauk",
  "Andada Pro",
  "Bellefair",
  "Odibee Sans",
  "Kurale",
  "Arizonia",
  "Lemon",
  "Annie Use Your Telescope",
  "Ms Madi",
  "Klee One",
  "Allerta",
  "Scada",
  "Pathway Extreme",
  "Knewave",
  "Castoro",
  "Bowlby One SC",
  "Ovo",
  "Carrois Gothic",
  "Rethink Sans",
  "Overlock",
  "Pattaya",
  "Hepta Slab",
  "Spline Sans",
  "Schoolbell",
  "Jomhuria",
  "Encode Sans Semi Condensed",
  "Kristi",
  "Wallpoet",
  "Inria Serif",
  "Fresca",
  "David Libre",
  "Oxygen Mono",
  "Short Stack",
  "Arbutus Slab",
  "Stardos Stencil",
  "Grand Hotel",
  "Sofia Sans Semi Condensed",
  "Enriqueta",
  "Big Shoulders Text",
  "Rasa",
  "Fahkwang",
  "Chonburi",
  "Proza Libre",
  "Metrophobic",
  "Limelight",
  "Koulen",
  "B612",
  "Waiting for the Sunrise",
  "Kosugi",
  "Petit Formal Script",
  "Encode Sans Expanded",
  "Poly",
  "UnifrakturMaguntia",
  "Wix Madefor Display",
  "Yesteryear",
  "Baloo Da 2",
  "Marmelad",
  "Niconne",
  "Contrail One",
  "McLaren",
  "Lateef",
  "Caladea",
  "Markazi Text",
  "Manjari",
  "Dawning of a New Day",
  "Rakkas",
  "Lexend Zetta",
  "Noto Sans Khmer",
  "Alegreya SC",
  "Montserrat Subrayada",
  "Rochester",
  "Average Sans",
  "Noto Serif Devanagari",
  "Lexend Exa",
  "Oooh Baby",
  "Inknut Antiqua",
  "Trirong",
  "Cormorant Upright",
  "Rosario",
  "Amiko",
  "Maitree",
  "Biryani",
  "Monsieur La Doulaise",
  "Bubblegum Sans",
  "Bungee Inline",
  "Calligraffitti",
  "M PLUS 2",
  "RocknRoll One",
  "Sigmar One",
  "Skranji",
  "Gurajada",
  "Love Ya Like A Sister",
  "Vesper Libre",
  "Glory",
  "Poetsen One",
  "Mansalva",
  "Hahmlet",
  "IBM Plex Sans KR",
  "Trocchi",
  "Azeret Mono",
  "Rambla",
  "Radley",
  "Fanwood Text",
  "IM Fell English",
  "Irish Grover",
  "Kelly Slab",
  "Voltaire",
  "Major Mono Display",
  "Miriam Libre",
  "B612 Mono",
  "Goudy Bookletter 1911",
  "Shantell Sans",
  "Ma Shan Zheng",
  "Cormorant SC",
  "Spectral SC",
  "Bentham",
  "Magra",
  "Geo",
  "Average",
  "Grenze Gotisch",
  "Zen Kurenaido",
  "Jockey One",
  "Antic Didone",
  "Sniglet",
  "Updock",
  "Solway",
  "Familjen Grotesk",
  "Mochiy Pop One",
  "Coustard",
  "Qwigley",
  "KoHo",
  "Style Script",
  "IM Fell DW Pica",
  "Quintessential",
  "DotGothic16",
  "Chelsea Market",
  "Fauna One",
  "Arya",
  "Copse",
  "Over the Rainbow",
  "Cambay",
  "Young Serif",
  "Dongle",
  "Agdasima",
  "Yusei Magic",
  "Noto Sans Meetei Mayek",
  "Modak",
  "Ephesis",
  "Noto Sans Georgian",
  "Saira Stencil One",
  "Pompiere",
  "Gabriela",
  "Meddon",
  "Poller One",
  "Noto Sans Armenian",
  "Capriola",
  "Marvel",
  "Molengo",
  "Aboreto",
  "Imbue",
  "Fjord One",
  "Encode Sans Semi Expanded",
  "Alike",
  "Pixelify Sans",
  "Nova Square",
  "Noto Sans Sinhala",
  "Farro",
  "Amethysta",
  "Bellota Text",
  "Sunflower",
  "Federo",
  "Aladin",
  "Turret Road",
  "Nova Mono",
  "Cutive",
  "Gotu",
  "Kaisei Decol",
  "IM Fell English SC",
  "Thasadith",
  "Brawler",
  "Hanuman",
  "Kadwa",
  "Gluten",
  "Aref Ruqaa",
  "Mountains of Christmas",
  "Gloock",
  "Sedgwick Ave",
  "Quando",
  "Baloo Thambi 2",
  "Della Respira",
  "Mogra",
  "Murecho",
  "Mr De Haviland",
  "Megrim",
  "Arima",
  "Agbalumo",
  "Prosto One",
  "Nokora",
  "Noto Sans Lao Looped",
  "Battambang",
  "Sansita Swashed",
  "Platypi",
  "Baloo Chettan 2",
  "IBM Plex Sans JP",
  "Expletus Sans",
  "Kodchasan",
  "Sue Ellen Francisco",
  "REM",
  "Libre Barcode 39 Extended Text",
  "Lekton",
  "Mouse Memoirs",
  "Baloo Tamma 2",
  "Supermercado One",
  "Aguafina Script",
  "Orelega One",
  "Red Rose",
  "Mallanna",
  "Notable",
  "Oleo Script Swash Caps",
  "Hurricane",
  "Fondamento",
  "Sumana",
  "Caprasimo",
  "Cambo",
  "Give You Glory",
  "Noto Sans Kannada",
  "Croissant One",
  "Anek Latin",
  "Flow Circular",
  "Reddit Mono",
  "Manuale",
  "Noto Emoji",
  "Asul",
  "Kufam",
  "ZCOOL QingKe HuangYou",
  "Patrick Hand SC",
  "Mukta Mahee",
  "Kablammo",
  "Instrument Serif",
  "Coiny",
  "Recursive",
  "Tiro Bangla",
  "Mukta Vaani",
  "Vina Sans",
  "ZCOOL XiaoWei",
  "Inder",
  "League Script",
  "Allan",
  "Tienne",
  "Tenali Ramakrishna",
  "Rampart One",
  "Vibur",
  "Noto Sans NKo Unjoined",
  "Potta One",
  "Zen Antique Soft",
  "Happy Monkey",
  "Bigshot One",
  "Vollkorn SC",
  "Atma",
  "Gugi",
  "Montaga",
  "Edu AU VIC WA NT Guides",
  "Suranna",
  "Piazzolla",
  "Zen Dots",
  "Euphoria Script",
  "Esteban",
  "Fuggles",
  "Ruslan Display",
  "Libre Caslon Display",
  "Noto Sans Telugu",
  "Hina Mincho",
  "Finger Paint",
  "Goblin One",
  "Just Me Again Down Here",
  "Noto Sans Myanmar",
  "Alike Angular",
  "Square Peg",
  "Imprima",
  "Kaisei Opti",
  "Crafty Girls",
  "Elsie",
  "Noto Sans Symbols",
  "Libre Barcode 128",
  "Averia Sans Libre",
  "Hi Melody",
  "Walter Turncoat",
  "Headland One",
  "Loved by the King",
  "Oregano",
  "Faster One",
  "NTR",
  "Clicker Script",
  "Gayathri",
  "BIZ UDPMincho",
  "Mirza",
  "Rouge Script",
  "Kaisei Tokumin",
  "Shojumaru",
  "Eater",
  "Puritan",
  "Qwitcher Grypen",
  "Share Tech",
  "Amarante",
  "Whisper",
  "Xanh Mono",
  "Slackey",
  "Kalnia",
  "Syne Mono",
  "Duru Sans",
  "Slabo 13px",
  "Salsa",
  "Cherry Cream Soda",
  "Dynalight",
  "Birthstone",
  "Baloo Bhai 2",
  "Metamorphous",
  "Numans",
  "Wendy One",
  "Almendra",
  "Sofadi One",
  "Bellota",
  "Corinthia",
  "Montez",
  "Carme",
  "Noto Sans Gujarati",
  "Raleway Dots",
  "Vast Shadow",
  "Bilbo Swash Caps",
  "Uncial Antiqua",
  "Monomaniac One",
  "Iceberg",
  "ADLaM Display",
  "Galada",
  "IM Fell Double Pica",
  "Kranky",
  "Road Rage",
  "Bubbler One",
  "Montagu Slab",
  "Bakbak One",
  "Mohave",
  "Dokdo",
  "Charmonman",
  "Bayon",
  "Goldman",
  "Balthazar",
  "Carlito",
  "Chivo Mono",
  "Gowun Dodum",
  "Lily Script One",
  "Martian Mono",
  "Harmattan",
  "Zen Antique",
  "Tilt Warp",
  "Anaheim",
  "Charis SIL",
  "Rubik Wet Paint",
  "Cormorant Unicase",
  "Afacad",
  "DynaPuff",
  "Dekko",
  "Playwrite GB S",
  "Noto Serif Malayalam",
  "Henny Penny",
  "Anybody",
  "Gamja Flower",
  "Artifika",
  "The Girl Next Door",
  "Mako",
  "Unkempt",
  "Chicle",
  "AR One Sans",
  "Gaegu",
  "Bruno Ace SC",
  "Sarpanch",
  "Red Hat Mono",
  "IBM Plex Sans Hebrew",
  "Kavivanar",
  "Fontdiner Swanky",
  "BhuTuka Expanded One",
  "Scheherazade New",
  "Flamenco",
  "Germania One",
  "Reddit Sans",
  "Viaoda Libre",
  "Orienta",
  "Codystar",
  "Shanti",
  "Nova Round",
  "Buenard",
  "Edu SA Beginner",
  "Zilla Slab Highlight",
  "Ledger",
  "Scope One",
  "Doppio One",
  "Mochiy Pop P One",
  "Sulphur Point",
  "Wire One",
  "Ubuntu Sans",
  "Fragment Mono",
  "Grape Nuts",
  "Smooch",
  "Baumans",
  "Ramaraja",
  "Monofett",
  "Redressed",
  "Playpen Sans",
  "Pavanam",
  "Asar",
  "Ceviche One",
  "Noto Serif Thai",
  "Lexend Peta",
  "Delius Unicase",
  "Original Surfer",
  "Freckle Face",
  "Anek Devanagari",
  "Reggae One",
  "Homenaje",
  "Varta",
  "Meow Script",
  "Kdam Thmor Pro",
  "Life Savers",
  "Freehand",
  "Overlock SC",
  "Voces",
  "Black And White Picture",
  "Katibeh",
  "Rubik Dirt",
  "Yuji Syuku",
  "Noto Sans Oriya",
  "IM Fell DW Pica SC",
  "Belgrano",
  "Libre Barcode 128 Text",
  "MonteCarlo",
  "Lovers Quarrel",
  "Rum Raisin",
  "Tauri",
  "Chango",
  "Cherry Swash",
  "Anek Bangla",
  "Chau Philomene One",
  "Moul",
  "WindSong",
  "Beth Ellen",
  "Trade Winds",
  "IM Fell French Canon",
  "Stick",
  "Lexend Mega",
  "Ruthie",
  "Ribeye",
  "Frijole",
  "Song Myung",
  "Lexend Giga",
  "Convergence",
  "Licorice",
  "Iceland",
  "Hachi Maru Pop",
  "Rubik Scribble",
  "East Sea Dokdo",
  "Noto Serif Khmer",
  "Noto Sans Gothic",
  "Modern Antiqua",
  "Bona Nova",
  "Comforter Brush",
  "Kantumruy Pro",
  "Atomic Age",
  "Rosarivo",
  "Akaya Kanadaka",
  "Peralta",
  "Medula One",
  "Crushed",
  "Swanky and Moo Moo",
  "ZCOOL KuaiLe",
  "Stylish",
  "Noto Sans Gurmukhi",
  "UnifrakturCook",
  "Chocolate Classical Sans",
  "Tiro Devanagari Hindi",
  "Miniver",
  "Macondo Swash Caps",
  "Strait",
  "Meera Inimai",
  "Radio Canada Big",
  "Emilys Candy",
  "Nosifer",
  "Sail",
  "Shippori Antique",
  "Sunshiney",
  "Noto Serif HK",
  "Baloo Bhaina 2",
  "Londrina Outline",
  "Barrio",
  "Ranchers",
  "Akronim",
  "Alkatra",
  "MedievalSharp",
  "Rhodium Libre",
  "Delius Swash Caps",
  "Tillana",
  "Tilt Neon",
  "Texturina",
  "Chela One",
  "Cute Font",
  "Yomogi",
  "Mystery Quest",
  "Mina",
  "IM Fell Great Primer",
  "Rationale",
  "Sancreek",
  "Baloo Tammudu 2",
  "Anek Tamil",
  "Fuzzy Bubbles",
  "Maiden Orange",
  "Fascinate Inline",
  "Akaya Telivigala",
  "Srisakdi",
  "Port Lligat Slab",
  "Gafata",
  "Sedgwick Ave Display",
  "Meie Script",
  "Tektur",
  "Timmana",
  "Cherry Bomb One",
  "Metal Mania",
  "Ewert",
  "Mooli",
  "Delicious Handrawn",
  "Denk One",
  "Fenix",
  "SUSE",
  "Nova Flat",
  "Sura",
  "Belanosima",
  "Miltonian Tattoo",
  "Afacad Flux",
  "Barriecito",
  "Kulim Park",
  "Vampiro One",
  "Londrina Shadow",
  "Carattere",
  "Moon Dance",
  "The Nautigal",
  "Habibi",
  "Seymour One",
  "Playwrite CU",
  "Noto Serif Telugu",
  "Handjet",
  "Noto Sans Ethiopic",
  "Stick No Bills",
  "Carrois Gothic SC",
  "Karantina",
  "Trykker",
  "Madimi One",
  "Asset",
  "Chathura",
  "Bodoni Moda SC",
  "Noto Serif Georgian",
  "Protest Strike",
  "IM Fell Great Primer SC",
  "IM Fell Double Pica SC",
  "Train One",
  "Stalemate",
  "Passions Conflict",
  "Sonsie One",
  "Borel",
  "Gulzar",
  "Caesar Dressing",
  "Abyssinica SIL",
  "M PLUS 1 Code",
  "Waterfall",
  "Kite One",
  "Astloch",
  "Birthstone Bounce",
  "Angkor",
  "Ysabeau Office",
  "Nova Slim",
  "Noto Sans Thai Looped",
  "Margarine",
  "Paprika",
  "Jomolhari",
  "Stint Ultra Expanded",
  "IM Fell French Canon SC",
  "Jolly Lodger",
  "Unlock",
  "Smythe",
  "Stoke",
  "Port Lligat Sans",
  "Redacted",
  "Sree Krushnadevaraya",
  "Farsan",
  "Keania One",
  "Donegal One",
  "Marko One",
  "Khmer",
  "Gentium Plus",
  "Kenia",
  "Cantora One",
  "Baskervville SC",
  "Trispace",
  "Noto Sans Buhid",
  "Ysabeau SC",
  "Chilanka",
  "Genos",
  "Underdog",
  "Eagle Lake",
  "Jacques Francois Shadow",
  "Noto Sans Anatolian Hieroglyphs",
  "Ribeye Marrow",
  "Vujahday Script",
  "Glass Antiqua",
  "Risque",
  "Edu VIC WA NT Beginner",
  "Nova Oval",
  "Engagement",
  "Solitreo",
  "Nova Cut",
  "Zhi Mang Xing",
  "Text Me One",
  "Girassol",
  "Suwannaphum",
  "Londrina Sketch",
  "Spline Sans Mono",
  "Imperial Script",
  "Simonetta",
  "Gorditas",
  "Junge",
  "Nova Script",
  "Alkalami",
  "New Rocker",
  "Noto Sans Math",
  "Liu Jian Mao Cao",
  "Bungee Spice",
  "Ruluko",
  "Noto Sans Symbols 2",
  "Rubik Doodle Shadow",
  "Bona Nova SC",
  "Miltonian",
  "Gemunu Libre",
  "Bilbo",
  "Festive",
  "Kavoon",
  "Sarina",
  "Comforter",
  "Cagliostro",
  "Kaisei HarunoUmi",
  "Long Cang",
  "New Tegomin",
  "Spirax",
  "Mrs Sheppards",
  "Braah One",
  "Big Shoulders Stencil Text",
  "Almendra SC",
  "Dorsa",
  "Sono",
  "Grenze",
  "Beau Rivage",
  "Anek Telugu",
  "Autour One",
  "Stint Ultra Condensed",
  "Tilt Prism",
  "Zen Tokyo Zoo",
  "Anton SC",
  "Fustat",
  "Bungee Hairline",
  "Protest Revolution",
  "Edu TAS Beginner",
  "Tac One",
  "Akatab",
  "Zain",
  "Lexend Tera",
  "Tiny5",
  "Inika",
  "Lacquer",
  "Kumar One Outline",
  "Noto Sans Glagolitic",
  "Sigmar",
  "Lavishly Yours",
  "Kirang Haerang",
  "Anek Gujarati",
  "Edu NSW ACT Foundation",
  "Rubik Moonrocks",
  "Peddana",
  "Joan",
  "Yaldevi",
  "Kotta One",
  "Danfo",
  "Poor Story",
  "Mynerve",
  "Koh Santepheap",
  "Elsie Swash Caps",
  "Jacques Francois",
  "Cairo Play",
  "Shalimar",
  "Condiment",
  "Gentium Book Plus",
  "Linden Hill",
  "Englebert",
  "Offside",
  "Milonga",
  "Fasthand",
  "Marhey",
  "Galdeano",
  "Inclusive Sans",
  "Griffy",
  "Yeon Sung",
  "Noto Sans Lao",
  "Tulpen One",
  "Smooch Sans",
  "Bahiana",
  "Shippori Antique B1",
  "Benne",
  "Dangrek",
  "BIZ UDMincho",
  "Lugrasimo",
  "IBM Plex Sans Thai Looped",
  "Noto Serif Kannada",
  "Tourney",
  "Emblema One",
  "Big Shoulders Stencil Display",
  "Bigelow Rules",
  "Arbutus",
  "Ysabeau Infant",
  "Buda",
  "Content",
  "Water Brush",
  "Joti One",
  "Finlandica",
  "Smokum",
  "Playwrite US Trad",
  "Anta",
  "Mingzat",
  "Poltawski Nowy",
  "Sahitya",
  "Wellfleet",
  "Ranga",
  "Gwendolyn",
  "Averia Gruesa Libre",
  "Kode Mono",
  "Ysabeau",
  "Tiro Devanagari Sanskrit",
  "Hubballi",
  "Odor Mean Chey",
  "Climate Crisis",
  "Piedra",
  "Bungee Outline",
  "Sometype Mono",
  "Noto Serif Oriya",
  "Libre Barcode 39 Extended",
  "Fascinate",
  "Praise",
  "Playwrite DE Grund",
  "Sixtyfour Convergence",
  "Truculenta",
  "Lancelot",
  "Federant",
  "Felipa",
  "Princess Sofia",
  "LXGW WenKai TC",
  "Qahiri",
  "Aoboshi One",
  "Aref Ruqaa Ink",
  "Encode Sans SC",
  "Luxurious Script",
  "Oldenburg",
  "Kumar One",
  "Romanesco",
  "Big Shoulders Inline Text",
  "Ravi Prakash",
  "Anek Gurmukhi",
  "Dr Sugiyama",
  "Phudu",
  "Bonheur Royale",
  "Rubik Glitch",
  "Flow Rounded",
  "Galindo",
  "Ballet",
  "Anek Kannada",
  "Butcherman",
  "GFS Neohellenic",
  "Protest Riot",
  "LXGW WenKai Mono TC",
  "Lumanosimo",
  "Gasoek One",
  "Erica One",
  "Lakki Reddy",
  "Stalinist One",
  "Arsenal SC",
  "Moderustic",
  "Preahvihear",
  "Alumni Sans Pinstripe",
  "Plaster",
  "Noto Sans Samaritan",
  "Miss Fajardose",
  "Blaka",
  "Noto Serif Armenian",
  "Metal",
  "Molle",
  "Flavors",
  "Jersey 20 Charted",
  "Snippet",
  "Rubik Distressed",
  "Diplomata SC",
  "Amiri Quran",
  "Teachers",
  "Mea Culpa",
  "Victor Mono",
  "Gideon Roman",
  "Foldit",
  "Freeman",
  "Sedan SC",
  "Reem Kufi Ink",
  "Noto Sans Osmanya",
  "Luxurious Roman",
  "IBM Plex Sans Devanagari",
  "Caramel",
  "Sirin Stencil",
  "Bacasime Antique",
  "Revalia",
  "Honk",
  "New Amsterdam",
  "Trochut",
  "Mr Bedfort",
  "Siemreap",
  "Noto Serif Hebrew",
  "Alumni Sans Inline One",
  "Chenla",
  "Noto Serif Khojki",
  "Rubik Iso",
  "Jersey 15",
  "Castoro Titling",
  "Jersey 25",
  "Hanalei Fill",
  "Single Day",
  "Butterfly Kids",
  "Babylonica",
  "Edu AU VIC WA NT Hand",
  "Gidugu",
  "BioRhyme Expanded",
  "Tiro Devanagari Marathi",
  "Fruktur",
  "Jim Nightshade",
  "Noto Sans Tai Viet",
  "Alumni Sans Collegiate One",
  "Libre Barcode EAN13 Text",
  "Almendra Display",
  "Neonderthaw",
  "Jacquard 24",
  "Bagel Fat One",
  "Aubrey",
  "Devonshire",
  "Darumadrop One",
  "Combo",
  "Uchen",
  "Diplomata",
  "Inspiration",
  "Kalnia Glaze",
  "Bokor",
  "Cactus Classical Serif",
  "Passero One",
  "Bruno Ace",
  "Tiro Tamil",
  "Micro 5",
  "Rubik Beastly",
  "Tiro Telugu",
  "Labrada",
  "Diphylleia",
  "Sevillana",
  "Reem Kufi Fun",
  "Noto Serif Tibetan",
  "Anek Odia",
  "Comme",
  "Fleur De Leah",
  "Grey Qo",
  "Noto Serif Sinhala",
  "Noto Serif Lao",
  "Yuji Boku",
  "Vibes",
  "Explora",
  "Zen Loop",
  "Dhurjati",
  "Splash",
  "Reddit Sans Condensed",
  "Purple Purse",
  "Ruge Boogie",
  "Send Flowers",
  "Tsukimi Rounded",
  "Tai Heritage Pro",
  "Orbit",
  "Rubik Glitch Pop",
  "Noto Music",
  "Noto Sans Adlam",
  "Lunasima",
  "Nuosu SIL",
  "Taprom",
  "Sedan",
  "Love Light",
  "Yuji Mai",
  "Nabla",
  "Redacted Script",
  "Rubik Doodle Triangles",
  "Noto Serif Balinese",
  "Noto Sans Javanese",
  "Noto Serif Gujarati",
  "Hedvig Letters Serif",
  "Rubik Vinyl",
  "Noto Sans Mongolian",
  "Jersey 10",
  "Jaro",
  "Moulpali",
  "Big Shoulders Inline Display",
  "Moirai One",
  "Langar",
  "Bonbon",
  "Oi",
  "Island Moments",
  "Noto Sans Tangsa",
  "Noto Sans Coptic",
  "Jersey 20",
  "Hedvig Letters Sans",
  "Matemasie",
  "Twinkle Star",
  "My Soul",
  "Edu AU VIC WA NT Dots",
  "Bahianita",
  "M PLUS Code Latin",
  "Flow Block",
  "Noto Sans Sora Sompeng",
  "Geostar Fill",
  "Rubik Spray Paint",
  "Geostar",
  "Rock 3D",
  "Petemoss",
  "Noto Sans Elbasan",
  "Tiro Gurmukhi",
  "Konkhmer Sleokchher",
  "Suravaram",
  "Dai Banna SIL",
  "Bungee Tint",
  "Sassy Frass",
  "Tiro Kannada",
  "Kolker Brush",
  "Protest Guerrilla",
  "Noto Sans Tagalog",
  "Jacquard 12",
  "Noto Serif Myanmar",
  "Noto Serif Vithkuqi",
  "Beiruti",
  "Palette Mosaic",
  "Wittgenstein",
  "Snowburst One",
  "Ga Maamli",
  "Noto Serif Ethiopic",
  "Noto Serif Tamil",
  "Noto Sans Canadian Aboriginal",
  "Playwrite IS",
  "Ruwudu",
  "Playwrite AR",
  "Hanalei",
  "Edu QLD Beginner",
  "Grechen Fuemen",
  "Estonia",
  "Moo Lah Lah",
  "Playwrite AU NSW",
  "Noto Sans Cypro Minoan",
  "Rubik 80s Fade",
  "Noto Traditional Nushu",
  "Playwrite FR Moderne",
  "Are You Serious",
  "Sankofa Display",
  "Noto Serif NP Hmong",
  "Noto Sans Carian",
  "Noto Sans Old Hungarian",
  "Noto Sans Sharada",
  "Workbench",
  "Shizuru",
  "Namdhinggo",
  "Syne Tactile",
  "Rubik Gemstones",
  "Noto Rashi Hebrew",
  "Playwrite BE VLG",
  "Noto Serif Tangut",
  "Noto Sans Nandinagari",
  "Cherish",
  "Ojuju",
  "Rubik Puddles",
  "Kings",
  "Noto Sans Cham",
  "Annapurna SIL",
  "Grandiflora One",
  "Ingrid Darling",
  "Playwrite MX",
  "Ole",
  "Noto Sans Syloti Nagri",
  "Noto Sans Thaana",
  "Sixtyfour",
  "Rubik Burned",
  "Noto Sans Nag Mundari",
  "Noto Sans Hanunoo",
  "Warnes",
  "Noto Sans Avestan",
  "Puppies Play",
  "Rubik Pixels",
  "Noto Sans Balinese",
  "Jacquarda Bastarda 9",
  "Playwrite AU SA",
  "Blaka Hollow",
  "Chokokutai",
  "Jacquard 12 Charted",
  "Playwrite PE",
  "Playwrite AU VIC",
  "Noto Sans Miao",
  "Playwrite NL",
  "Gajraj One",
  "Noto Sans Old Italic",
  "Tapestry",
  "Slackside One",
  "Noto Serif Gurmukhi",
  "Rubik Marker Hatch",
  "Playwrite AT",
  "Noto Sans Chorasmian",
  "Ubuntu Sans Mono",
  "Noto Sans Tifinagh",
  "Playwrite DK Loopet",
  "Noto Serif Ottoman Siyaq",
  "Playwrite HR",
  "Playwrite SK",
  "Noto Sans Imperial Aramaic",
  "Playwrite ES",
  "Playwrite DK Uloopet",
  "Playwrite PL",
  "Playwrite HR Lijeva",
  "Rubik Microbe",
  "Noto Serif Toto",
  "Noto Sans Khojki",
  "Noto Sans Cherokee",
  "Noto Sans Old Permic",
  "Playwrite PT",
  "Playwrite NG Modern",
  "Blaka Ink",
  "Playwrite CL",
  "Noto Sans Egyptian Hieroglyphs",
  "Noto Serif Khitan Small Script",
  "Playwrite BE WAL",
  "Playwrite NZ",
  "Noto Sans New Tai Lue",
  "Playwrite HU",
  "Noto Sans Vai",
  "Playwrite IT Moderna",
  "Noto Sans Ol Chiki",
  "Noto Sans Old North Arabian",
  "Yuji Hentaigana Akari",
  "Rubik Maps",
  "Playwrite AU TAS",
  "Rubik Storm",
  "Noto Sans Deseret",
  "Noto Serif Yezidi",
  "Playwrite ZA",
  "Lisu Bosa",
  "Playwrite US Modern",
  "Noto Sans Syriac Eastern",
  "Playwrite CZ",
  "Rubik Broken Fax",
  "Noto Sans Bamum",
  "Playwrite AU QLD",
  "Playwrite CO",
  "Noto Sans Kawi",
  "Playwrite VN",
  "Noto Sans Kaithi",
  "Noto Sans Sundanese",
  "Noto Sans Newa",
  "Noto Sans Batak",
  "Playwrite ES Deco",
  "Noto Sans Tamil Supplement",
  "Noto Sans Adlam Unjoined",
  "Playwrite FR Trad",
  "Kay Pho Du",
  "Maname",
  "Jaini",
  "Noto Sans Vithkuqi",
  "Noto Serif Ahom",
  "Noto Sans Medefaidrin",
  "Noto Serif Old Uyghur",
  "Rubik Maze",
  "Noto Serif Grantha",
  "Noto Sans Marchen",
  "Playwrite NO",
  "Noto Sans Old Turkic",
  "Noto Sans Tagbanwa",
  "Playwrite RO",
  "Noto Sans Old Persian",
  "Noto Sans Lydian",
  "Noto Sans NKo",
  "Noto Sans Yi",
  "Noto Sans Tai Tham",
  "Jersey 15 Charted",
  "Narnoor",
  "Playwrite IN",
  "Playwrite ID",
  "Noto Sans Grantha",
  "Playwrite IE",
  "Playwrite DE LA",
  "Rubik Lines",
  "Noto Sans Bassa Vah",
  "Playwrite GB J",
  "Noto Sans Osage",
  "Noto Sans Lisu",
  "Playwrite CA",
  "Playwrite DE VA",
  "Noto Sans Warang Citi",
  "Noto Sans Tai Le",
  "Noto Sans Cuneiform",
  "Noto Znamenny Musical Notation",
  "Noto Sans Indic Siyaq Numbers",
  "Noto Sans Brahmi",
  "Micro 5 Charted",
  "Noto Sans Inscriptional Pahlavi",
  "Jersey 10 Charted",
  "Playwrite DE SAS",
  "Noto Sans Duployan",
  "Playwrite TZ",
  "Jaini Purva",
  "Noto Sans Zanabazar Square",
  "Playwrite BR",
  "Noto Sans Takri",
  "Noto Sans Mro",
  "Playwrite IT Trad",
  "Noto Sans Multani",
  "Padyakke Expanded One",
  "Noto Sans Siddham",
  "Linefont",
  "Jersey 25 Charted",
  "Noto Serif Dogra",
  "Wavefont",
  "Noto Sans Palmyrene",
  "Noto Serif Makasar",
  "Noto Sans Old South Arabian",
  "Noto Sans Chakma",
  "Noto Sans Phoenician",
  "Noto Sans Kharoshthi",
  "Noto Sans Rejang",
  "Noto Sans Limbu",
  "Noto Sans Runic",
  "Noto Sans Inscriptional Parthian",
  "Noto Sans Psalter Pahlavi",
  "Noto Sans Linear A",
  "Noto Sans Mayan Numerals",
  "Noto Sans Phags Pa",
  "Noto Sans Wancho",
  "Jacquard 24 Charted",
  "Noto Sans Lepcha",
  "Noto Sans Hanifi Rohingya",
  "Noto Sans Cypriot",
  "Yuji Hentaigana Akebono",
  "Noto Sans Syriac",
  "Noto Sans Buginese",
  "Noto Sans Nabataean",
  "Noto Sans Modi",
  "Jacquarda Bastarda 9 Charted",
  "Noto Sans Pahawh Hmong",
  "Noto Sans Linear B",
  "Noto Sans Mandaic",
  "Noto Sans Elymaic",
  "Noto Sans Lycian",
  "Noto Sans Nushu",
  "Noto Sans Gunjala Gondi",
  "Noto Sans Shavian",
  "Noto Sans Old Sogdian",
  "Noto Sans Caucasian Albanian",
  "Noto Sans Saurashtra",
  "Noto Sans Sogdian",
  "Noto Sans Pau Cin Hau",
  "Noto Sans Mende Kikakui",
  "Noto Sans Ogham",
  "Noto Sans Soyombo",
  "Noto Sans Hatran",
  "Noto Sans Kayah Li",
  "Noto Sans Manichaean",
  "Noto Sans Mahajani",
  "Noto Sans Meroitic",
  "Noto Sans Tirhuta",
  "Noto Sans SignWriting",
  "Noto Sans Khudawadi",
  "Noto Sans Bhaiksuki",
  "Noto Sans Ugaritic",
  "Noto Sans Masaram Gondi",
  "Yarndings 12",
  "Yarndings 12 Charted",
  "Yarndings 20",
  "Yarndings 20 Charted",
];
