export default {
  guide: [{ slug: "get-started", title: "Get started", description: "" }],
  components: [
    { slug: "button", title: "Button", description: "Example" },
    { slug: "checkbox", title: "Checkbox", description: "Example" },
    { slug: "command", title: "Command", description: "Example" },
    {
      slug: "dialog",
      title: "Dialog",
      description: "Example\ndialog animated",
    },
    { slug: "form", title: "Form", description: "Example" },
    { slug: "heading", title: "Heading", description: "Example" },
    { slug: "menu", title: "Menu", description: "Example" },
    { slug: "radio", title: "Radio", description: "Example" },
    { slug: "separator", title: "Separator", description: "example" },
    { slug: "tab", title: "Tab", description: "Example" },
    { slug: "tooltip", title: "Tooltip", description: "Example" },
  ],
  examples: [
    { slug: "button", title: "button", description: "Example" },
    { slug: "button-as-div", title: "button-as-div", description: "Example" },
    { slug: "button-as-link", title: "button-as-link", description: "Example" },
    { slug: "checkbox", title: "checkbox", description: "Example" },
    {
      slug: "checkbox-as-button",
      title: "checkbox-as-button",
      description: "Example",
    },
    {
      slug: "checkbox-controlled",
      title: "checkbox-controlled",
      description: "Example",
    },
    {
      slug: "checkbox-custom",
      title: "checkbox-custom",
      description: "Example",
    },
    { slug: "checkbox-group", title: "checkbox-group", description: "Example" },
    { slug: "checkbox-state", title: "checkbox-state", description: "Example" },
    { slug: "collection", title: "collection", description: "Example" },
    { slug: "combobox", title: "combobox", description: "Example" },
    {
      slug: "combobox-animated",
      title: "combobox-animated",
      description: "Example",
    },
    {
      slug: "combobox-cancel",
      title: "combobox-cancel",
      description: "Example",
    },
    {
      slug: "combobox-disclosure",
      title: "combobox-disclosure",
      description: "Example",
    },
    { slug: "combobox-group", title: "combobox-group", description: "Example" },
    {
      slug: "combobox-matches",
      title: "combobox-matches",
      description: "Example",
    },
    {
      slug: "combobox-multiple",
      title: "combobox-multiple",
      description: "Example",
    },
    {
      slug: "combobox-textarea",
      title: "combobox-textarea",
      description: "Example",
    },
    { slug: "command", title: "command", description: "Example" },
    {
      slug: "command-enter-disabled",
      title: "command-enter-disabled",
      description: "Example",
    },
    {
      slug: "command-space-disabled",
      title: "command-space-disabled",
      description: "Example",
    },
    {
      slug: "composite-hover-virtual-focus-events",
      title: "composite-hover-virtual-focus-events",
      description: "Example",
    },
    { slug: "dialog", title: "dialog", description: "Example" },
    {
      slug: "dialog-animated",
      title: "dialog-animated",
      description: "Example",
    },
    { slug: "dialog-details", title: "dialog-details", description: "Example" },
    {
      slug: "dialog-react-router",
      title: "dialog-react-router",
      description: "Example",
    },
    { slug: "disclosure", title: "disclosure", description: "Example" },
    { slug: "focus-trap", title: "focus-trap", description: "Example" },
    {
      slug: "focus-trap-region",
      title: "focus-trap-region",
      description: "Example",
    },
    { slug: "form", title: "form", description: "Example" },
    {
      slug: "form-select",
      title: "Form with Select",
      description:
        "Example demonstrating how to use the Select component with a Form with native browser validation.",
    },
    { slug: "group", title: "group", description: "Example" },
    { slug: "heading", title: "heading", description: "Example" },
    { slug: "hovercard", title: "hovercard", description: "Example" },
    {
      slug: "hovercard-disclosure",
      title: "hovercard-disclosure",
      description: "Example",
    },
    { slug: "menu", title: "menu", description: "Example" },
    { slug: "menu-bar", title: "menu-bar", description: "Example" },
    { slug: "menu-combobox", title: "menu-combobox", description: "Example" },
    {
      slug: "menu-context-menu",
      title: "menu-context-menu",
      description: "Example",
    },
    {
      slug: "menu-dialog-animated",
      title: "menu-dialog-animated",
      description: "Example",
    },
    {
      slug: "menu-framer-motion",
      title: "menu-framer-motion",
      description: "Example",
    },
    {
      slug: "menu-item-checkbox",
      title: "menu-item-checkbox",
      description: "Example",
    },
    {
      slug: "menu-item-radio",
      title: "menu-item-radio",
      description: "Example",
    },
    { slug: "menu-nested", title: "menu-nested", description: "Example" },
    { slug: "menu-slide", title: "menu-slide", description: "Example" },
    { slug: "popover", title: "popover", description: "Example" },
    { slug: "popover-flip", title: "popover-flip", description: "Example" },
    {
      slug: "popover-focus-within",
      title: "popover-focus-within",
      description: "Example",
    },
    {
      slug: "popover-responsive",
      title: "popover-responsive",
      description: "Example",
    },
    {
      slug: "popover-selection",
      title: "popover-selection",
      description: "Example",
    },
    {
      slug: "popover-standalone",
      title: "popover-standalone",
      description: "Example",
    },
    { slug: "portal", title: "portal", description: "Example" },
    { slug: "portal-lazy", title: "portal-lazy", description: "Example" },
    { slug: "radio", title: "radio", description: "Example" },
    { slug: "select", title: "select", description: "Example" },
    {
      slug: "select-animated",
      title: "select-animated",
      description: "Example",
    },
    {
      slug: "select-autofill",
      title: "select-autofill",
      description: "Example",
    },
    {
      slug: "select-combobox",
      title: "select-combobox",
      description: "Example",
    },
    { slug: "select-grid", title: "select-grid", description: "Example" },
    { slug: "select-group", title: "select-group", description: "Example" },
    {
      slug: "select-item-custom",
      title: "select-item-custom",
      description: "Example",
    },
    {
      slug: "select-multiple",
      title: "select-multiple",
      description: "Example",
    },
    { slug: "separator", title: "separator", description: "Example" },
    { slug: "tab", title: "tab", description: "Example" },
    {
      slug: "tab-react-router",
      title: "tab-react-router",
      description: "Example",
    },
    { slug: "toolbar", title: "toolbar", description: "Example" },
    { slug: "toolbar-select", title: "toolbar-select", description: "Example" },
    { slug: "tooltip", title: "tooltip", description: "Example" },
    {
      slug: "tooltip-placement",
      title: "tooltip-placement",
      description: "Example",
    },
    {
      slug: "tooltip-timeout",
      title: "tooltip-timeout",
      description: "Example",
    },
    { slug: "playground", title: "playground", description: "Example" },
    {
      slug: "playground-client",
      title: "playground-client",
      description: "Example",
    },
    {
      slug: "playground-code",
      title: "playground-code",
      description: "Example",
    },
    {
      slug: "playground-tabs",
      title: "playground-tabs",
      description: "Example",
    },
  ],
  blog: [{ slug: "first-post", title: "First post", description: "Test" }],
};
