module.exports = {
  guide: [{ slug: "get-started", title: "Get started", description: "" }],
  components: [
    { slug: "button", title: "Button", description: "Example" },
    { slug: "checkbox", title: "Checkbox", description: "Example" },
    {
      slug: "command",
      title: "Command",
      description: "Example",
      group: "Abstract Components",
    },
    {
      slug: "dialog",
      title: "Dialog",
      description: "Example\ndialog animated",
    },
    { slug: "form", title: "Form", description: "Example" },
    { slug: "heading", title: "Heading", description: "Example" },
    { slug: "menu", title: "Menu", description: "Example" },
    { slug: "radio", title: "Radio", description: "Example" },
    { slug: "separator", title: "Separator", description: "example" },
    { slug: "tab", title: "Tab", description: "Example" },
    { slug: "tooltip", title: "Tooltip", description: "Example" },
  ],
  examples: [
    {
      slug: "button",
      title: "button",
      description: "Example",
      group: "Button",
    },
    {
      slug: "button-as-div",
      title: "button-as-div",
      description: "Example",
      group: "Button",
    },
    {
      slug: "button-as-link",
      title: "button-as-link",
      description: "Example",
      group: "Button",
    },
    {
      slug: "checkbox",
      title: "checkbox",
      description: "Example",
      group: "Checkbox",
    },
    {
      slug: "checkbox-as-button",
      title: "checkbox-as-button",
      description: "Example",
      group: "Checkbox",
    },
    {
      slug: "checkbox-controlled",
      title: "checkbox-controlled",
      description: "Example",
      group: "Checkbox",
    },
    {
      slug: "checkbox-custom",
      title: "checkbox-custom",
      description: "Example",
      group: "Checkbox",
    },
    {
      slug: "checkbox-group",
      title: "checkbox-group",
      description: "Example",
      group: "Checkbox",
    },
    {
      slug: "checkbox-state",
      title: "checkbox-state",
      description: "Example",
      group: "Checkbox",
    },
    {
      slug: "collection",
      title: "collection",
      description: "Example",
      group: "Collection",
    },
    {
      slug: "combobox",
      title: "combobox",
      description: "Example",
      group: "Combobox",
    },
    {
      slug: "combobox-animated",
      title: "combobox-animated",
      description: "Example",
      group: "Combobox",
    },
    {
      slug: "combobox-cancel",
      title: "combobox-cancel",
      description: "Example",
      group: "Combobox",
    },
    {
      slug: "combobox-disclosure",
      title: "combobox-disclosure",
      description: "Example",
      group: "Combobox",
    },
    {
      slug: "combobox-group",
      title: "combobox-group",
      description: "Example",
      group: "Combobox",
    },
    {
      slug: "combobox-matches",
      title: "combobox-matches",
      description: "Example",
      group: "Combobox",
    },
    {
      slug: "combobox-multiple",
      title: "combobox-multiple",
      description: "Example",
      group: "Combobox",
    },
    {
      slug: "combobox-textarea",
      title: "combobox-textarea",
      description: "Example",
      group: "Combobox",
    },
    {
      slug: "command",
      title: "command",
      description: "Example",
      group: "Command",
    },
    {
      slug: "command-enter-disabled",
      title: "command-enter-disabled",
      description: "Example",
      group: "Command",
    },
    {
      slug: "command-space-disabled",
      title: "command-space-disabled",
      description: "Example",
      group: "Command",
    },
    {
      slug: "composite-hover-virtual-focus-events",
      title: "composite-hover-virtual-focus-events",
      description: "Example",
      group: "Composite",
    },
    {
      slug: "dialog",
      title: "dialog",
      description: "Example",
      group: "Dialog",
    },
    {
      slug: "dialog-animated",
      title: "dialog-animated",
      description: "Example",
      group: "Dialog",
    },
    {
      slug: "dialog-details",
      title: "dialog-details",
      description: "Example",
      group: "Dialog",
    },
    {
      slug: "dialog-react-router",
      title: "dialog-react-router",
      description: "Example",
      group: "Dialog",
    },
    {
      slug: "disclosure",
      title: "disclosure",
      description: "Example",
      group: "Disclosure",
    },
    {
      slug: "focus-trap",
      title: "focus-trap",
      description: "Example",
      group: "FocusTrap",
    },
    {
      slug: "focus-trap-region",
      title: "focus-trap-region",
      description: "Example",
      group: "FocusTrap",
    },
    { slug: "form", title: "form", description: "Example", group: "Form" },
    {
      slug: "form-select",
      title: "Form with Select",
      description:
        "A Select component rendered as a FormField using the built-in browser validation.",
      group: "Form",
    },
    { slug: "group", title: "group", description: "Example", group: "Group" },
    {
      slug: "heading",
      title: "heading",
      description: "Example",
      group: "Heading",
    },
    {
      slug: "hovercard",
      title: "hovercard",
      description: "Example",
      group: "Hovercard",
    },
    {
      slug: "hovercard-disclosure",
      title: "hovercard-disclosure",
      description: "Example",
      group: "Hovercard",
    },
    { slug: "menu", title: "menu", description: "Example", group: "Menu" },
    {
      slug: "menu-bar",
      title: "menu-bar",
      description: "Example",
      group: "Menu",
    },
    {
      slug: "menu-combobox",
      title: "menu-combobox",
      description: "Example",
      group: "Menu",
    },
    {
      slug: "menu-context-menu",
      title: "menu-context-menu",
      description: "Example",
      group: "Menu",
    },
    {
      slug: "menu-dialog-animated",
      title: "menu-dialog-animated",
      description: "Example",
      group: "Menu",
    },
    {
      slug: "menu-framer-motion",
      title: "menu-framer-motion",
      description: "Example",
      group: "Menu",
    },
    {
      slug: "menu-item-checkbox",
      title: "menu-item-checkbox",
      description: "Example",
      group: "Menu",
    },
    {
      slug: "menu-item-radio",
      title: "menu-item-radio",
      description: "Example",
      group: "Menu",
    },
    {
      slug: "menu-nested",
      title: "menu-nested",
      description: "Example",
      group: "Menu",
    },
    {
      slug: "menu-slide",
      title: "menu-slide",
      description: "Example",
      group: "Menu",
    },
    {
      slug: "popover",
      title: "popover",
      description: "Example",
      group: "Popover",
    },
    {
      slug: "popover-flip",
      title: "popover-flip",
      description: "Example",
      group: "Popover",
    },
    {
      slug: "popover-focus-within",
      title: "popover-focus-within",
      description: "Example",
      group: "Popover",
    },
    {
      slug: "popover-responsive",
      title: "popover-responsive",
      description: "Example",
      group: "Popover",
    },
    {
      slug: "popover-selection",
      title: "popover-selection",
      description: "Example",
      group: "Popover",
    },
    {
      slug: "popover-standalone",
      title: "popover-standalone",
      description: "Example",
      group: "Popover",
    },
    {
      slug: "portal",
      title: "portal",
      description: "Example",
      group: "Portal",
    },
    {
      slug: "portal-lazy",
      title: "portal-lazy",
      description: "Example",
      group: "Portal",
    },
    { slug: "radio", title: "radio", description: "Example", group: "Radio" },
    {
      slug: "select",
      title: "select",
      description: "Example",
      group: "Select",
    },
    {
      slug: "select-animated",
      title: "select-animated",
      description: "Example",
      group: "Select",
    },
    {
      slug: "select-autofill",
      title: "select-autofill",
      description: "Example",
      group: "Select",
    },
    {
      slug: "select-combobox",
      title: "select-combobox",
      description: "Example",
      group: "Select",
    },
    {
      slug: "select-combobox-focus-within",
      title: "select-combobox-focus-within",
      description: "Example",
      group: "Select",
    },
    {
      slug: "select-grid",
      title: "select-grid",
      description: "Example",
      group: "Select",
    },
    {
      slug: "select-group",
      title: "select-group",
      description: "Example",
      group: "Select",
    },
    {
      slug: "select-item-custom",
      title: "select-item-custom",
      description: "Example",
      group: "Select",
    },
    {
      slug: "select-multiple",
      title: "select-multiple",
      description: "Example",
      group: "Select",
    },
    {
      slug: "separator",
      title: "separator",
      description: "Example",
      group: "Separator",
    },
    { slug: "tab", title: "tab", description: "Example", group: "Tab" },
    {
      slug: "tab-react-router",
      title: "tab-react-router",
      description: "Example",
      group: "Tab",
    },
    {
      slug: "toolbar",
      title: "toolbar",
      description: "Example",
      group: "Toolbar",
    },
    {
      slug: "toolbar-select",
      title: "toolbar-select",
      description: "Example",
      group: "Toolbar",
    },
    {
      slug: "tooltip",
      title: "tooltip",
      description: "Example",
      group: "Tooltip",
    },
    {
      slug: "tooltip-placement",
      title: "tooltip-placement",
      description: "Example",
      group: "Tooltip",
    },
    {
      slug: "tooltip-timeout",
      title: "tooltip-timeout",
      description: "Example",
      group: "Tooltip",
    },
    { slug: "playground", title: "playground", description: "Example" },
    {
      slug: "playground-client",
      title: "playground-client",
      description: "Example",
    },
    {
      slug: "playground-code",
      title: "playground-code",
      description: "Example",
    },
    {
      slug: "playground-tabs",
      title: "playground-tabs",
      description: "Example",
    },
  ],
  blog: [{ slug: "first-post", title: "First post", description: "Test" }],
};
