import { press, q } from "@ariakit/test";

test("navigate with keyboard", async () => {
  await press.Tab();
  expect(q.button("Bold")).toHaveFocus();
  await press.ArrowRight();
  await press.ArrowRight();
  await press.ArrowRight();
  expect(q.combobox("Text alignment")).toHaveFocus();
  await press.ArrowRight();
  expect(q.button("Bold")).toHaveFocus();
  await press.End();
  expect(q.combobox("Text alignment")).toHaveFocus();
  expect(q.listbox()).not.toBeInTheDocument();
  await press.ArrowDown();
  expect(q.listbox()).toBeVisible();
  expect(q.option("Align Left")).toHaveFocus();
  await press.ArrowDown();
  expect(q.option("Align Center")).toHaveFocus();
  await press.ShiftTab();
  expect(q.combobox("Text alignment")).toHaveFocus();
  expect(q.listbox()).toBeVisible();
  await press.Tab();
  expect(q.option("Align Center")).toHaveFocus();
  await press.Enter();
  expect(q.listbox()).not.toBeInTheDocument();
  expect(q.combobox("Text alignment")).toHaveFocus();
  await press.ArrowLeft();
  expect(q.button("Underline")).toHaveFocus();
});
