// Automatically generated
const COMBOBOX_MENU_STATE_KEYS = [
  "baseId",
  "unstable_idCountRef",
  "unstable_virtual",
  "rtl",
  "orientation",
  "groups",
  "currentId",
  "loop",
  "wrap",
  "unstable_moves",
  "unstable_angular",
  "unstable_hasActiveWidget",
  "items",
  "menuRole",
  "inputValue",
  "minValueLength",
  "currentValue",
  "values",
  "limit",
  "matches",
  "list",
  "inline",
  "autoSelect",
  "visible",
  "setBaseId",
  "unregisterItem",
  "registerGroup",
  "unregisterGroup",
  "move",
  "next",
  "previous",
  "up",
  "down",
  "first",
  "last",
  "sort",
  "unstable_setVirtual",
  "setRTL",
  "setOrientation",
  "setCurrentId",
  "setLoop",
  "setWrap",
  "reset",
  "unstable_setHasActiveWidget",
  "registerItem",
  "setInputValue",
  "setMinValueLength",
  "setValues",
  "setLimit",
  "setList",
  "setInline",
  "setAutoSelect",
] as const;
const COMBOBOX_MENU_GRID_STATE_KEYS = [
  ...COMBOBOX_MENU_STATE_KEYS,
  "columns",
  "setColumns",
] as const;
const COMBOBOX_STATE_KEYS = [
  ...COMBOBOX_MENU_STATE_KEYS,
  "animated",
  "animating",
  "modal",
  "unstable_disclosureRef",
  "unstable_referenceRef",
  "unstable_popoverRef",
  "unstable_arrowRef",
  "unstable_popoverStyles",
  "unstable_arrowStyles",
  "unstable_originalPlacement",
  "unstable_update",
  "placement",
  "show",
  "hide",
  "toggle",
  "setVisible",
  "setAnimated",
  "stopAnimation",
  "setModal",
  "place",
] as const;
const COMBOBOX_GRID_STATE_KEYS = [
  ...COMBOBOX_MENU_GRID_STATE_KEYS,
  ...COMBOBOX_STATE_KEYS,
] as const;
export const COMBOBOX_KEYS = COMBOBOX_GRID_STATE_KEYS;
export const COMBOBOX_GRID_CELL_KEYS = COMBOBOX_KEYS;
export const COMBOBOX_GRID_ROW_KEYS = COMBOBOX_GRID_CELL_KEYS;
export const COMBOBOX_ITEM_KEYS = [...COMBOBOX_GRID_ROW_KEYS, "value"] as const;
export const COMBOBOX_MENU_KEYS = COMBOBOX_GRID_ROW_KEYS;
export const COMBOBOX_OPTION_KEYS = COMBOBOX_MENU_KEYS;
export const COMBOBOX_POPOVER_KEYS = COMBOBOX_OPTION_KEYS;
