// Automatically generated by ../../../../scripts/build/utils.js
const ID_STATE_KEYS = [
  "baseId",
  "unstable_idCountRef",
  "unstable_setBaseId",
] as const;
export const ID_KEYS = [...ID_STATE_KEYS, "id"] as const;
