/**
 * @license
 * Copyright 2025-present Ariakit FZ-LLC. All Rights Reserved.
 *
 * This software is proprietary. See the license.md file in the root of this
 * package for licensing terms.
 *
 * SPDX-License-Identifier: UNLICENSED
 */
import fs from "node:fs/promises";
import {
  basename,
  dirname,
  isAbsolute,
  join,
  relative,
  resolve,
} from "node:path";
import { fileURLToPath } from "node:url";
import { invariant } from "@ariakit/utils";
import type { AstroConfig, AstroIntegration } from "astro";
import type { Plugin, ViteDevServer } from "vite";
import {
  discoverPreviews,
  isPreviewEntryFile,
  resolvePreviewRoots,
} from "./preview-discovery.ts";
import type {
  DiscoveredPreview,
  PreviewDiscoveryOptions,
} from "./preview-discovery.ts";
import type { Framework } from "./schemas.ts";

const PREVIEW_REGISTRY_MODULE_ID = "virtual:ariakit-previews/registry";

interface PreviewCodegenParams {
  codegenDir: string;
  previews: DiscoveredPreview[];
}

interface PreviewIntegrationParams {
  config: AstroConfig;
  codegenDir: string;
  options: PreviewDiscoveryOptions;
}

interface GeneratedPreviewModule {
  id: string;
  file: string;
}

interface PreviewCodegenResult {
  changed: boolean;
  registryFile: string;
}

function toPosixPath(path: string) {
  return path.replace(/\\/g, "/");
}

function getRelativeImportPath(fromFile: string, toFile: string) {
  let path = toPosixPath(relative(dirname(fromFile), toFile));
  if (!path.startsWith(".")) {
    path = `./${path}`;
  }
  return path;
}

function getPascalCase(value: string) {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function getFrameworkVariable(framework: Framework) {
  return getPascalCase(framework) || "Preview";
}

function getPreviewFile(previewsDir: string, id: string) {
  const segments = id.split("/");
  for (const segment of segments) {
    invariant(segment, `Invalid preview id: ${id}`);
    invariant(segment !== "." && segment !== "..", `Invalid preview id: ${id}`);
  }
  return join(previewsDir, ...segments, "preview.astro");
}

async function writeFileIfChanged(file: string, content: string) {
  try {
    const current = await fs.readFile(file, "utf8");
    if (current === content) return false;
  } catch {}
  await fs.mkdir(dirname(file), { recursive: true });
  await fs.writeFile(file, content);
  return true;
}

function generatePreviewWrapper(preview: DiscoveredPreview, file: string) {
  const frameworks = preview.frameworks.filter((framework) => {
    return !!preview.entryFiles[framework];
  });
  const componentImports: string[] = [];
  const sourceImports: string[] = [];
  const sourceEntries: string[] = [];
  const componentEntries: string[] = [];
  for (const framework of frameworks) {
    const entryFile = preview.entryFiles[framework];
    invariant(entryFile, `Missing ${framework} entry file for ${preview.id}`);
    const variable = getFrameworkVariable(framework);
    const importPath = getRelativeImportPath(file, entryFile);
    componentImports.push(
      `import ${variable}Example from ${JSON.stringify(importPath)};`,
    );
    sourceImports.push(
      `import source${variable} from ${JSON.stringify(`${importPath}?source`)};`,
    );
    sourceEntries.push(`  ${JSON.stringify(framework)}: source${variable},`);
    componentEntries.push(
      `  <${variable}Example client:load slot=${JSON.stringify(framework)} />`,
    );
  }
  return `---\nimport PreviewFramework from "#app/components/preview-framework.astro";\n${componentImports.join("\n")}\n\n${sourceImports.join("\n")}\n\nexport const source = {\n${sourceEntries.join("\n")}\n};\n---\n\n<PreviewFramework>\n${componentEntries.join("\n")}\n</PreviewFramework>\n`;
}

function generateRegistry(
  modules: GeneratedPreviewModule[],
  registryFile: string,
) {
  const cases = modules
    .map((module) => {
      const importPath = getRelativeImportPath(registryFile, module.file);
      return `    case ${JSON.stringify(module.id)}:\n      return import(${JSON.stringify(importPath)});`;
    })
    .join("\n");
  return `// This file is generated by app/src/lib/preview-integration.ts.\n\nexport async function loadPreview(id: string) {\n  switch (id) {\n${cases}\n    default:\n      throw new Error("Unknown preview: " + id);\n  }\n}\n`;
}

async function getGeneratedPreviewFiles(dir: string) {
  const files: string[] = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return files;
  }
  for (const entry of entries) {
    const file = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await getGeneratedPreviewFiles(file)));
      continue;
    }
    if (entry.isFile() && entry.name === "preview.astro") {
      files.push(file);
    }
  }
  return files;
}

async function removeFileAndEmptyParents(file: string, root: string) {
  await fs.rm(file, { force: true });
  let dir = dirname(file);
  while (dir !== root && isInDirectory(dir, root)) {
    let entries: string[];
    try {
      entries = await fs.readdir(dir);
    } catch {
      return;
    }
    if (entries.length > 0) break;
    try {
      await fs.rmdir(dir);
    } catch {
      return;
    }
    dir = dirname(dir);
  }
}

export async function writePreviewCodegen({
  codegenDir,
  previews,
}: PreviewCodegenParams): Promise<PreviewCodegenResult> {
  const previewsDir = join(codegenDir, "previews");
  const registryFile = join(codegenDir, "registry.ts");
  const generatedModules: GeneratedPreviewModule[] = [];
  const generatedFiles = new Set<string>();
  let changed = false;
  for (const preview of previews) {
    if (Object.keys(preview.entryFiles).length === 0) continue;
    const file = getPreviewFile(previewsDir, preview.id);
    generatedFiles.add(file);
    changed =
      (await writeFileIfChanged(file, generatePreviewWrapper(preview, file))) ||
      changed;
    generatedModules.push({ id: preview.id, file });
  }
  for (const file of await getGeneratedPreviewFiles(previewsDir)) {
    if (generatedFiles.has(file)) continue;
    await removeFileAndEmptyParents(file, previewsDir);
    changed = true;
  }
  changed =
    (await writeFileIfChanged(
      registryFile,
      generateRegistry(generatedModules, registryFile),
    )) || changed;
  return { changed, registryFile };
}

async function generatePreviewCodegen({
  config,
  codegenDir,
  options,
}: PreviewIntegrationParams) {
  const previews = await discoverPreviews({
    root: config.root,
    srcDir: config.srcDir,
    ...options,
  });
  return writePreviewCodegen({ codegenDir, previews });
}

function isInDirectory(file: string, dir: string) {
  const relativePath = relative(dir, file);
  return (
    relativePath === "" ||
    (!!relativePath &&
      !relativePath.startsWith("..") &&
      !isAbsolute(relativePath))
  );
}

export function shouldRegeneratePreview(
  file: string,
  roots: ReturnType<typeof resolvePreviewRoots>,
  metadataFileName = "preview.json",
) {
  const filename = basename(file);
  if (filename !== metadataFileName) {
    if (!isPreviewEntryFile(filename)) return false;
  }
  return roots.some((root) => isInDirectory(file, root.dir));
}

function shouldRegenerate(file: string, params: PreviewIntegrationParams) {
  const roots = resolvePreviewRoots({
    root: params.config.root,
    srcDir: params.config.srcDir,
    ...params.options,
  });
  return shouldRegeneratePreview(file, roots, params.options.metadataFileName);
}

function getPreviewImportId(file: string, params: PreviewIntegrationParams) {
  const roots = resolvePreviewRoots({
    root: params.config.root,
    srcDir: params.config.srcDir,
    ...params.options,
  });
  for (const root of roots) {
    if (!isInDirectory(file, root.dir)) continue;
    const id = toPosixPath(relative(root.dir, dirname(file)));
    if (!id) return undefined;
    return id;
  }
  return undefined;
}

function resolvePreviewImport(
  id: string,
  importer: string | undefined,
  params: PreviewIntegrationParams,
) {
  const specifier = id.split("?")[0] ?? id;
  if (!specifier.endsWith("/preview.astro")) return undefined;
  const file = isAbsolute(specifier)
    ? specifier
    : specifier.startsWith("#app/")
      ? join(
          fileURLToPath(params.config.srcDir),
          specifier.slice("#app/".length),
        )
      : importer
        ? resolve(dirname(importer), specifier)
        : undefined;
  if (!file) return undefined;
  const previewId = getPreviewImportId(file, params);
  if (!previewId) return undefined;
  return getPreviewFile(join(params.codegenDir, "previews"), previewId);
}

function invalidateRegistry(server: ViteDevServer, registryFile: string) {
  const module =
    server.moduleGraph.getModuleById(registryFile) ??
    server.moduleGraph.getModuleById(PREVIEW_REGISTRY_MODULE_ID);
  if (module) {
    server.moduleGraph.invalidateModule(module);
  }
  server.ws.send({ type: "full-reload" });
}

function previewCodegenPlugin(params: PreviewIntegrationParams): Plugin {
  let registryFile = join(params.codegenDir, "registry.ts");
  let pendingRegeneration = Promise.resolve();
  const regenerate = async () => {
    const result = await generatePreviewCodegen(params);
    registryFile = result.registryFile;
    return result.changed;
  };
  const queueRegeneration = () => {
    const result = pendingRegeneration.then(regenerate, regenerate);
    pendingRegeneration = result.then(
      () => undefined,
      () => undefined,
    );
    return result;
  };
  return {
    name: "vite-plugin-ariakit-previews",
    resolveId(id, importer) {
      if (id === PREVIEW_REGISTRY_MODULE_ID) {
        return registryFile;
      }
      return resolvePreviewImport(id, importer, params);
    },
    configureServer(server) {
      const roots = resolvePreviewRoots({
        root: params.config.root,
        srcDir: params.config.srcDir,
        ...params.options,
      });
      server.watcher.add(roots.map((root) => root.dir));
      const handleChange = async (file: string) => {
        if (!shouldRegenerate(file, params)) return;
        const changed = await queueRegeneration();
        if (changed) {
          invalidateRegistry(server, registryFile);
        }
      };
      server.watcher.on("add", handleChange);
      server.watcher.on("change", handleChange);
      server.watcher.on("unlink", handleChange);
    },
  };
}

export function previewIntegration(
  options: PreviewDiscoveryOptions = {},
): AstroIntegration {
  return {
    name: "ariakit-previews",
    hooks: {
      "astro:config:setup": async ({
        addWatchFile,
        config,
        createCodegenDir,
        updateConfig,
      }) => {
        const codegenDir = fileURLToPath(createCodegenDir());
        const params = { config, codegenDir, options };
        await generatePreviewCodegen(params);
        for (const root of resolvePreviewRoots({
          root: config.root,
          srcDir: config.srcDir,
          ...options,
        })) {
          addWatchFile(root.dir);
        }
        updateConfig({
          vite: {
            plugins: [previewCodegenPlugin(params)],
          },
        });
      },
    },
  };
}
