export const pages = {
  Guide: [
    { label: "Getting Started", path: "/guide/getting-started" },
    { label: "Styling", path: "/guide/styling" },
    { label: "Composition", path: "/guide/composition" },
    { label: "Component providers", path: "/guide/component-providers" },
    { label: "Component stores", path: "/guide/component-stores" },
    { label: "Coding guidelines", path: "/guide/coding-guidelines" },
  ],
  Components: [
    { label: "Button", path: "/components/button" },
    { label: "Checkbox", path: "/components/checkbox" },
    { label: "Combobox", path: "/components/combobox" },
    { label: "Dialog", path: "/components/dialog" },
    { label: "Disclosure", path: "/components/disclosure" },
    { label: "Form", path: "/components/form" },
    { label: "Heading", path: "/components/heading" },
    { label: "Hovercard", path: "/components/hovercard" },
    { label: "Menu", path: "/components/menu" },
    { label: "Menubar", path: "/components/menubar" },
    { label: "Popover", path: "/components/popover" },
    { label: "Radio", path: "/components/radio" },
    { label: "Select", path: "/components/select" },
    { label: "Tab", path: "/components/tab" },
    { label: "Toolbar", path: "/components/toolbar" },
    { label: "Tooltip", path: "/components/tooltip" },
  ],
  Examples: [
    { label: "Custom Checkbox", path: "/examples/checkbox-custom" },
    { label: "Checkbox group", path: "/examples/checkbox-group" },
    { label: "Animated combobox", path: "/examples/combobox-animated" },
    { label: "ComboboxCancel", path: "/examples/combobox-cancel" },
    { label: "ComboboxDisclosure", path: "/examples/combobox-disclosure" },
    { label: "Combobox filtering", path: "/examples/combobox-filtering" },
    { label: "ComboboxGroup", path: "/examples/combobox-Group" },
    { label: "Combobox with links", path: "/examples/combobox-links" },
    { label: "Radix UI Combobox", path: "/examples/combobox-radix" },
    { label: "Animated Dialog", path: "/examples/dialog-animated" },
    { label: "Warning on Dialog hide", path: "/examples/dialog-hide-warning" },
    { label: "Dialog with Menu", path: "/examples/dialog-menu" },
    { label: "Nested Dialog", path: "/examples/dialog-nested" },
    { label: "Radix UI Dialog", path: "/examples/dialog-radix" },
    { label: "Form with Select", path: "/examples/form-select" },
    { label: "Menu with Combobox", path: "/examples/menu-combobox" },
    { label: "Menu with Framer Motion", path: "/examples/menu-framer-motion" },
    { label: "MenuItemCheckbox", path: "/examples/menu-item-checkbox" },
    { label: "Submenu", path: "/examples/menu-nested" },
    { label: "Submenu with Combobox", path: "/examples/menu-nested-combobox" },
    { label: "Menu with Tooltip", path: "/examples/menu-tooltip" },
    { label: "Navigation Menubar", path: "/examples/menubar-navigation" },
    { label: "Lazy Popover", path: "/examples/popover-lazy" },
    { label: "Selection Popover", path: "/examples/popover-selection" },
    { label: "Animated Select", path: "/examples/select-animated" },
    { label: "Select with Combobox", path: "/examples/select-combobox" },
    { label: "Select with custom items", path: "/examples/select-item-custom" },
    { label: "Multi-Select", path: "/examples/select-multiple" },
    { label: "Tab with React Router", path: "/examples/tab-react-router" },
    { label: "Tab with Next.js App Router", path: "/examples/tab-next-router" },
    { label: "Toolbar with Select", path: "/examples/toolbar-select" },
  ],
};

export const flatPages = Object.entries(pages).flatMap(([category, pages]) =>
  pages.map((page) => ({ ...page, category })),
);
