// Automatically generated by ../../../../scripts/build/utils.js
const CHECKBOX_STATE_KEYS = ["state", "setState"] as const;
export const CHECKBOX_KEYS = [
  ...CHECKBOX_STATE_KEYS,
  "value",
  "checked",
] as const;
