export default [
  { name: "Apple", type: "Fruits" },
  { name: "Avocado", type: "Fruits" },
  { name: "Banana", type: "Fruits" },
  { name: "Cherry", type: "Fruits" },
  { name: "Coconut", type: "Fruits" },
  { name: "Grape", type: "Fruits" },
  { name: "Kiwi", type: "Fruits" },
  { name: "Lemon", type: "Fruits" },
  { name: "Lime", type: "Fruits" },
  { name: "Mango", type: "Fruits" },
  { name: "Orange", type: "Fruits" },
  { name: "Papaya", type: "Fruits" },
  { name: "Pear", type: "Fruits" },
  { name: "Pineapple", type: "Fruits" },
  { name: "Pomegranate", type: "Fruits" },
  { name: "Strawberry", type: "Fruits" },
  { name: "Watermelon", type: "Fruits" },

  { name: "Bacon", type: "Meat" },
  { name: "Beef", type: "Meat" },
  { name: "Chicken", type: "Meat" },
  { name: "Fish", type: "Meat" },
  { name: "Ham", type: "Meat" },
  { name: "Lamb", type: "Meat" },
  { name: "Pork", type: "Meat" },
  { name: "Sausage", type: "Meat" },
  { name: "Turkey", type: "Meat" },

  { name: "Bread", type: "Bakery" },
  { name: "Cake", type: "Bakery" },
  { name: "Cookie", type: "Bakery" },
  { name: "Croissant", type: "Bakery" },
  { name: "Donut", type: "Bakery" },
  { name: "Eclair", type: "Bakery" },
  { name: "Fondant", type: "Bakery" },
  { name: "Gelato", type: "Bakery" },
  { name: "Muffin", type: "Bakery" },
  { name: "Pie", type: "Bakery" },
  { name: "Pudding", type: "Bakery" },
  { name: "Scone", type: "Bakery" },
  { name: "Souffle", type: "Bakery" },
  { name: "Tart", type: "Bakery" },
  { name: "Waffle", type: "Bakery" },

  { name: "Butter", type: "Dairy" },
  { name: "Cheese", type: "Dairy" },
  { name: "Cream", type: "Dairy" },
  { name: "Egg", type: "Dairy" },
  { name: "Milk", type: "Dairy" },
  { name: "Sour cream", type: "Dairy" },
  { name: "Yogurt", type: "Dairy" },

  { name: "Beer", type: "Beverages" },
  { name: "Brandy", type: "Beverages" },
  { name: "Cider", type: "Beverages" },
  { name: "Coffee", type: "Beverages" },
  { name: "Cognac", type: "Beverages" },
  { name: "Gin", type: "Beverages" },
  { name: "Juice", type: "Beverages" },
  { name: "Liqueur", type: "Beverages" },
  { name: "Milkshake", type: "Beverages" },
  { name: "Rum", type: "Beverages" },
  { name: "Sake", type: "Beverages" },
  { name: "Sherry", type: "Beverages" },
  { name: "Soda", type: "Beverages" },
  { name: "Tea", type: "Beverages" },
  { name: "Tequila", type: "Beverages" },
  { name: "Vodka", type: "Beverages" },
  { name: "Water", type: "Beverages" },
  { name: "Whiskey", type: "Beverages" },
  { name: "Wine", type: "Beverages" },
];
