name: install-node-modules
description: Install node modules

runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        cache: true
        run_install: false

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
