// Automatically generated by scripts/build/keys.js
export const CREATE_HOOK_KEYS = [
  "name",
  "compose",
  "useState",
  "useOptions",
  "useProps",
  "useComposeOptions",
  "useComposeProps",
  "propsAreEqual",
  "keys",
] as const;
