import type { Locator } from "@playwright/test";

export interface CaptureSection {
  /** Keep this identity when its selector title or layout changes. */
  key: string;
  title: string;
}

const listCaptureSections: readonly CaptureSection[] = [
  { key: "default", title: "Default" },
  { key: "ordered-rows", title: "Ordered rows" },
  { key: "bulleted-rows", title: "Bulleted rows" },
  { key: "unordered-blocks", title: "Unordered blocks" },
  { key: "ordered-steps", title: "Ordered steps" },
  { key: "steps-without-a-guide", title: "Steps without a guide" },
  { key: "sections", title: "Sections" },
  { key: "deep-sections", title: "Deep sections" },
  { key: "nested-list", title: "Nested list" },
  { key: "nested-steps", title: "Nested steps" },
  { key: "track", title: "Track" },
  { key: "timeline", title: "Timeline" },
  { key: "checklist", title: "Checklist" },
  { key: "step-cards", title: "Step cards" },
  { key: "link-rows", title: "Link rows" },
  { key: "disclosure-steps", title: "Disclosure steps" },
  { key: "disclosure-badges", title: "Disclosure badges" },
  { key: "disclosure-status", title: "Disclosure status" },
  { key: "release-notes", title: "Release notes" },
  { key: "inside-prose", title: "Inside prose" },
  { key: "dense-rows", title: "Dense rows" },
  { key: "large-text", title: "Large text" },
  { key: "checklist-on-a-brand-layer", title: "Checklist on a brand layer" },
  { key: "status-legend", title: "Status legend" },
  { key: "right-to-left-steps", title: "Right to left steps" },
  {
    key: "list-disclosure-optional-button",
    title: "list-disclosure-optional-button",
  },
  { key: "list-item-marker-checked", title: "list-item-marker-checked" },
  { key: "raw-marker-edge", title: "Raw marker edge" },
  { key: "markers-with-optional-props", title: "Markers with optional props" },
];

// These are authored capture identities. Do not regenerate keys from titles.
export const pageCaptureSections: Record<string, readonly CaptureSection[]> = {
  "ui/badge/page": [
    { key: "default", title: "Default" },
    { key: "brand", title: "Brand" },
    { key: "custom-color", title: "Custom color" },
    { key: "solid", title: "Solid" },
    { key: "inverted", title: "Inverted" },
    { key: "outline", title: "Outline" },
    { key: "flat-tint", title: "Flat tint" },
    { key: "strong-ring", title: "Strong ring" },
    { key: "raw-ring", title: "Raw ring" },
    { key: "dashed-border", title: "Dashed border" },
    { key: "hue", title: "Hue" },
    { key: "tag-shape", title: "Tag shape" },
    { key: "large", title: "Large" },
    { key: "counts", title: "Counts" },
    { key: "count-sizes", title: "Count sizes" },
    { key: "shape-padding", title: "Shape padding" },
    { key: "in-running-text", title: "In running text" },
    { key: "auto-size-in-a-heading", title: "Auto size in a heading" },
    { key: "leading-icon", title: "Leading icon" },
    { key: "trailing-icon", title: "Trailing icon" },
    { key: "avatar", title: "Avatar" },
    { key: "trailing-count", title: "Trailing count" },
    { key: "truncated-label", title: "Truncated label" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
  ],
  "ui/button/page": [
    { key: "default", title: "Default" },
    { key: "layer-disabled", title: "Layer disabled" },
    { key: "lifted", title: "Lifted" },
    { key: "pushed", title: "Pushed" },
    { key: "contrast", title: "Contrast" },
    { key: "desaturated", title: "Desaturated" },
    { key: "brand", title: "Brand" },
    { key: "danger", title: "Danger" },
    { key: "custom-color", title: "Custom color" },
    { key: "inverted", title: "Inverted" },
    { key: "bevel", title: "Bevel" },
    { key: "ring-borders", title: "Ring borders" },
    { key: "danger-bevel", title: "Danger bevel" },
    { key: "submit", title: "Submit" },
    { key: "extra-small", title: "Extra small" },
    { key: "extra-large", title: "Extra large" },
    { key: "pill", title: "Pill" },
    { key: "icon-only", title: "Icon only" },
    { key: "as-a-link", title: "As a link" },
    { key: "small-slot", title: "Small slot" },
    { key: "large-slot", title: "Large slot" },
    { key: "close-slot-gap", title: "Close slot gap" },
    { key: "painted-icon-slot", title: "Painted icon slot" },
    { key: "initial-avatar", title: "Initial avatar" },
    { key: "large-avatar-initials", title: "Large avatar initials" },
    {
      key: "avatar-with-normal-line-height",
      title: "Avatar with normal line height",
    },
    { key: "composed-avatar-initials", title: "Composed avatar initials" },
    { key: "fragment-avatar-initials", title: "Fragment avatar initials" },
    { key: "avatar-shape", title: "Avatar shape" },
    { key: "image-avatar", title: "Image avatar" },
    { key: "count-badge", title: "Count badge" },
    { key: "badge-hue", title: "Badge hue" },
    { key: "keyboard-shortcut", title: "Keyboard shortcut" },
    { key: "floating-badge", title: "Floating badge" },
    { key: "right-to-left", title: "Right to left" },
    { key: "label-and-description", title: "Label and description" },
    { key: "clamped-description", title: "Clamped description" },
    { key: "horizontal-content", title: "Horizontal content" },
    { key: "disabled", title: "Disabled" },
    { key: "disabled-upload-label", title: "Disabled upload label" },
    { key: "disabled-avatars", title: "Disabled avatars" },
    { key: "disabled-fieldset", title: "Disabled fieldset" },
    { key: "nested-badge-and-avatar", title: "Nested badge and avatar" },
    { key: "disabled-bevel", title: "Disabled bevel" },
    { key: "disabled-brand", title: "Disabled brand" },
    { key: "focusable-disabled", title: "Focusable disabled" },
    { key: "disabled-inverted", title: "Disabled inverted" },
    { key: "thin-focus-ring", title: "Thin focus ring" },
    { key: "thick-focus-ring", title: "Thick focus ring" },
    { key: "offset-focus-ring", title: "Offset focus ring" },
    { key: "highlighted-focus", title: "Highlighted focus" },
    { key: "bordered-group", title: "Bordered group" },
    { key: "joined-buttons", title: "Joined buttons" },
    { key: "stretched-group", title: "Stretched group" },
    { key: "spaced-group", title: "Spaced group" },
    { key: "small-group", title: "Small group" },
    { key: "wrapping-group", title: "Wrapping group" },
    { key: "pipe-separators", title: "Pipe separators" },
    { key: "chevron-separators", title: "Chevron separators" },
    { key: "full-height-separators", title: "Full-height separators" },
    { key: "thick-separators", title: "Thick separators" },
    { key: "segmented-control", title: "Segmented control" },
    { key: "glider-ring", title: "Glider ring" },
    { key: "horizontal-bar-glider", title: "Horizontal bar glider" },
    { key: "vertical-bar-glider", title: "Vertical bar glider" },
    { key: "current-link-gliders", title: "Current link gliders" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
    { key: "glider", title: "Glider" },
    { key: "independent", title: "Independent" },
    { key: "joined-vertical", title: "Joined vertical" },
    { key: "horizontal", title: "Horizontal" },
    { key: "stretched", title: "Stretched" },
    { key: "padded", title: "Padded" },
    { key: "spaced", title: "Spaced" },
    { key: "vertical", title: "Vertical" },
    { key: "wrapped", title: "Wrapped" },
    { key: "numeric-zero", title: "Numeric zero" },
    { key: "pixel-zero", title: "Pixel zero" },
    { key: "rem-zero", title: "Rem zero" },
    { key: "calculated-zero", title: "Calculated zero" },
    { key: "control-surfaces", title: "Control surfaces" },
    { key: "dimmed-button", title: "Dimmed button" },
  ],
  "ui/checkbox/page": [
    { key: "default", title: "Default" },
    { key: "checkbox-field", title: "Checkbox field" },
    { key: "field-with-description", title: "Field with description" },
    { key: "disabled-field", title: "Disabled field" },
    { key: "disabled-checked-field", title: "Disabled checked field" },
    { key: "large-field", title: "Large field" },
    { key: "select-all", title: "Select all" },
    { key: "checkbox-card", title: "Checkbox card" },
    { key: "disabled-checked-card", title: "Disabled checked card" },
    { key: "mixed-card", title: "Mixed card" },
    { key: "card-with-description", title: "Card with description" },
    { key: "card-with-avatar", title: "Card with avatar" },
    { key: "stacked-tiles", title: "Stacked tiles" },
    { key: "card-grid", title: "Card grid" },
    { key: "floating-check", title: "Floating check" },
    { key: "round-check", title: "Round check" },
    { key: "custom-mark", title: "Custom mark" },
    { key: "filter-chips", title: "Filter chips" },
    { key: "fields-on-a-brand-layer", title: "Fields on a brand layer" },
    { key: "cards-on-a-brand-layer", title: "Cards on a brand layer" },
    { key: "right-to-left-tile", title: "Right to left tile" },
    { key: "tile-with-a-badge", title: "Tile with a badge" },
    {
      key: "card-grid-with-an-optional-role",
      title: "Card grid with an optional role",
    },
    { key: "card-badge", title: "Card badge" },
    { key: "disabled-card-badges", title: "Disabled card badges" },
    { key: "disabled-field-labels", title: "Disabled field labels" },
  ],
  "ui/code/page": [
    { key: "default", title: "Default" },
    { key: "in-a-heading", title: "In a heading" },
    { key: "in-secondary-text", title: "In secondary text" },
    { key: "in-a-link", title: "In a link" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
    { key: "colored-layer", title: "Colored layer" },
    { key: "inverted", title: "Inverted" },
    { key: "transparent-layer", title: "Transparent layer" },
    { key: "no-layer", title: "No layer" },
    { key: "stronger-ring", title: "Stronger ring" },
    { key: "raw-brand-edge", title: "Raw brand edge" },
    { key: "long-content", title: "Long content" },
  ],
  "ui/combobox/page": [
    { key: "default", title: "Default" },
    { key: "open-suggestions", title: "Open suggestions" },
    { key: "groups", title: "Groups" },
    { key: "custom-items", title: "Custom items" },
    { key: "command-items", title: "Command items" },
    { key: "empty-state", title: "Empty state" },
    { key: "default-select", title: "Default select" },
    { key: "open-select", title: "Open select" },
    { key: "in-a-form", title: "In a form" },
    { key: "rich-items", title: "Rich items" },
    { key: "icons", title: "Icons" },
    { key: "bevel-select", title: "Bevel select" },
    { key: "flat-select", title: "Flat select" },
    { key: "chevron-first", title: "Chevron first" },
    { key: "without-chevron", title: "Without chevron" },
    { key: "placeholder", title: "Placeholder" },
    { key: "status-select", title: "Status select" },
    { key: "disabled-select", title: "Disabled select" },
    { key: "multiple-selection", title: "Multiple selection" },
    { key: "selection-count", title: "Selection count" },
    { key: "searchable-select", title: "Searchable select" },
    { key: "scrollable-search", title: "Scrollable search" },
    { key: "long-list", title: "Long list" },
    { key: "field-boundaries", title: "Field boundaries" },
    {
      key: "input-combobox-optional-props",
      title: "input-combobox-optional-props",
    },
    { key: "combobox-select-content", title: "combobox-select-content" },
    {
      key: "combobox-select-content-conditional-content",
      title: "combobox-select-content conditional content",
    },
    { key: "custom-selection-icons", title: "Custom selection icons" },
    { key: "combobox-item-highlight", title: "combobox-item-highlight" },
  ],
  "ui/dialog/page": [
    { key: "default", title: "Default" },
    { key: "close-button", title: "Close button" },
    { key: "form", title: "Form" },
    {
      key: "scroll-body-with-header-and-footer",
      title: "Scroll body with header and footer",
    },
    { key: "long-content", title: "Long content" },
    { key: "custom-max-width", title: "Custom max width" },
    { key: "brand-surface", title: "Brand surface" },
    { key: "nested-dialogs", title: "Nested dialogs" },
    {
      key: "dismiss-with-an-optional-label",
      title: "Dismiss with an optional label",
    },
  ],
  "ui/disclosure/page": [
    { key: "default", title: "Default" },
    { key: "no-shape", title: "No shape" },
    { key: "trailing-badge", title: "Trailing badge" },
    { key: "slots-with-description", title: "Slots with description" },
    { key: "bordered", title: "Bordered" },
    { key: "filled", title: "Filled" },
    { key: "bevel-button", title: "Bevel button" },
    { key: "indicator-after-the-label", title: "Indicator after the label" },
    { key: "no-indicator", title: "No indicator" },
    { key: "icon", title: "Icon" },
    { key: "description", title: "Description" },
    { key: "icon-size", title: "Icon size" },
    { key: "split", title: "Split" },
    { key: "spaced-content", title: "Spaced content" },
    { key: "guide", title: "Guide" },
    { key: "prose-body", title: "Prose body" },
    { key: "group", title: "Group" },
    { key: "framed-group", title: "Framed group" },
    { key: "nested", title: "Nested" },
    { key: "composed-parts", title: "Composed parts" },
    { key: "controlled", title: "Controlled" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
    { key: "right-to-left", title: "Right to left" },
    { key: "disclosure-button-store", title: "Disclosure button store" },
    { key: "explicit-labels", title: "Explicit labels" },
    {
      key: "disclosure-optional-content",
      title: "Disclosure optional content",
    },
    {
      key: "named-description-only-button",
      title: "Named description-only button",
    },
  ],
  "ui/heading/page": [
    { key: "semantic-levels", title: "Semantic levels" },
    { key: "visual-level", title: "Visual level" },
    { key: "size-override", title: "Size override" },
    { key: "wrapped-title", title: "Wrapped title" },
    { key: "flow-margins", title: "Flow margins" },
    { key: "brand-text", title: "Brand text" },
    { key: "accent-hue", title: "Accent hue" },
    { key: "on-an-inverted-layer", title: "On an inverted layer" },
    { key: "permalink", title: "Permalink" },
  ],
  "ui/input/page": [
    { key: "default", title: "Default" },
    { key: "labeled-field-with-hint", title: "Labeled field with hint" },
    { key: "invalid", title: "Invalid" },
    { key: "disabled", title: "Disabled" },
    { key: "subtle-edge", title: "Subtle edge" },
    { key: "pill", title: "Pill" },
    { key: "compact", title: "Compact" },
    { key: "small", title: "Small" },
    { key: "thick-focus-ring", title: "Thick focus ring" },
    { key: "textarea", title: "Textarea" },
    { key: "date-field", title: "Date field" },
    { key: "field-with-leading-icon", title: "Field with leading icon" },
    { key: "grouped-input", title: "Grouped Input" },
    {
      key: "share-link-with-copy-button",
      title: "Share link with copy button",
    },
    { key: "search-trigger", title: "Search trigger" },
    {
      key: "inline-form-with-submit-button",
      title: "Inline form with submit button",
    },
    { key: "control-sizes", title: "Control sizes" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
    { key: "field-with-help-popup", title: "Field with help popup" },
    { key: "grouped-native-fields", title: "Grouped native fields" },
    {
      key: "field-with-leading-reset-button",
      title: "Field with leading reset button",
    },
  ],
  "ui/kbd/page": [
    { key: "default", title: "Default" },
    { key: "shortcut-list", title: "Shortcut list" },
    { key: "small-text", title: "Small text" },
    { key: "large-text", title: "Large text" },
    { key: "brand-cap", title: "Brand cap" },
    { key: "inverted-cap", title: "Inverted cap" },
    { key: "transparent-cap", title: "Transparent cap" },
    { key: "brand-edge", title: "Brand edge" },
    { key: "raw-brand-edge", title: "Raw brand edge" },
    { key: "fixed-edge-weight", title: "Fixed edge weight" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
    { key: "on-an-inverted-layer", title: "On an inverted layer" },
  ],
  "ui/layer/page": [{ key: "layer-color-values", title: "Layer color values" }],
  "ui/link/page": [
    { key: "default", title: "Default" },
    { key: "wrapped-across-lines", title: "Wrapped across lines" },
    { key: "trailing-icon", title: "Trailing icon" },
    { key: "rendered-as-a-button", title: "Rendered as a button" },
    { key: "danger", title: "Danger" },
    { key: "custom-color", title: "Custom color" },
    { key: "derived-from-the-layer", title: "Derived from the layer" },
    { key: "inherited-color", title: "Inherited color" },
    { key: "stronger-contrast", title: "Stronger contrast" },
    { key: "offset-focus-ring", title: "Offset focus ring" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
    { key: "on-an-inverted-layer", title: "On an inverted layer" },
  ],
  "ui/list/page": listCaptureSections,
  "ui/nav/page": [
    { key: "rows", title: "Rows" },
    { key: "touching-rows", title: "Touching rows" },
    { key: "icons", title: "Icons" },
    { key: "groups", title: "Groups" },
    { key: "command-row", title: "Command row" },
    { key: "disclosures", title: "Disclosures" },
    {
      key: "disclosures-without-icons-ltr",
      title: "Disclosures without icons (ltr)",
    },
    {
      key: "disclosures-without-icons-rtl",
      title: "Disclosures without icons (rtl)",
    },
    { key: "nested-disclosures", title: "Nested disclosures" },
    { key: "bevel-glider", title: "Bevel glider" },
    { key: "bar-on-the-guide-line", title: "Bar on the guide line" },
    { key: "bar-beside-a-cover", title: "Bar beside a cover" },
    { key: "bar-without-a-guide", title: "Bar without a guide" },
    { key: "bar-at-the-end", title: "Bar at the end" },
    {
      key: "end-bar-across-sections-ltr",
      title: "End bar across sections (ltr)",
    },
    {
      key: "end-bar-across-sections-rtl",
      title: "End bar across sections (rtl)",
    },
    { key: "sidebar", title: "Sidebar" },
    { key: "right-to-left-groups", title: "Right to left groups" },
    { key: "right-to-left-disclosures", title: "Right to left disclosures" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
    { key: "current-page-in-a-dialog", title: "Current page in a dialog" },
    {
      key: "section-across-an-unrelated-provider",
      title: "Section across an unrelated provider",
    },
    { key: "explicit-disclosure-parts", title: "Explicit disclosure parts" },
    { key: "disclosure-badges", title: "Disclosure badges" },
    { key: "custom-label-styles", title: "Custom label styles" },
    {
      key: "optional-navigation-headings",
      title: "Optional navigation headings",
    },
    { key: "horizontal-navigation", title: "Horizontal navigation" },
    { key: "link-item-ownership", title: "Link item ownership" },
    { key: "link-descriptions", title: "Link descriptions" },
    { key: "wide-icons", title: "Wide icons" },
  ],
  "ui/popover/page": [
    { key: "default", title: "Default" },
    { key: "with-an-arrow", title: "With an arrow" },
    { key: "medium-shadow", title: "Medium shadow" },
    { key: "no-shadow", title: "No shadow" },
    { key: "without-an-edge", title: "Without an edge" },
    { key: "compact-frame", title: "Compact frame" },
    { key: "brand-callout", title: "Brand callout" },
    { key: "close-button", title: "Close button" },
    { key: "form-with-a-dismiss", title: "Form with a dismiss" },
    { key: "scroll", title: "Scroll" },
    { key: "opened-on-click", title: "Opened on click" },
    {
      key: "dismiss-with-an-optional-label",
      title: "Dismiss with an optional label",
    },
  ],
  "ui/progress/page": [
    { key: "default", title: "Default" },
    { key: "no-value", title: "No value" },
    { key: "fill-colors", title: "Fill colors" },
    { key: "custom-fill", title: "Custom fill" },
    { key: "thick-bar", title: "Thick bar" },
    { key: "hairline-bar", title: "Hairline bar" },
    { key: "bold-edge", title: "Bold edge" },
    { key: "borderless-track", title: "Borderless track" },
    { key: "soft-corners", title: "Soft corners" },
    { key: "tinted-track", title: "Tinted track" },
    { key: "ring-with-label", title: "Ring with label" },
    { key: "thick-ring", title: "Thick ring" },
    { key: "outlined-ring", title: "Outlined ring" },
    { key: "inline-status-ring", title: "Inline status ring" },
    { key: "completed-ring", title: "Completed ring" },
    { key: "ring-at-zero", title: "Ring at zero" },
    { key: "ring-on-a-brand-layer", title: "Ring on a brand layer" },
    { key: "value-change", title: "Value change" },
  ],
  "ui/prose/page": [
    { key: "default", title: "Default" },
    { key: "compact-gap", title: "Compact gap" },
    { key: "small-type", title: "Small type" },
    { key: "large-type", title: "Large type" },
    {
      key: "callout-on-an-inverted-layer",
      title: "Callout on an inverted layer",
    },
  ],
  "ui/radio/page": [
    { key: "group", title: "Group" },
    { key: "descriptions", title: "Descriptions" },
    { key: "small-horizontal-group", title: "Small horizontal group" },
    { key: "inline-radios", title: "Inline radios" },
    { key: "disabled-option", title: "Disabled option" },
    { key: "disabled-group", title: "Disabled group" },
    { key: "group-on-a-brand-layer", title: "Group on a brand layer" },
    { key: "cards", title: "Cards" },
    { key: "stacked-tiles", title: "Stacked tiles" },
    { key: "check-mark", title: "Check mark" },
    { key: "disabled-card", title: "Disabled card" },
    { key: "disabled-card-grid", title: "Disabled card grid" },
    { key: "disabled-card-slots", title: "Disabled card slots" },
    { key: "disabled-card-badges", title: "Disabled card badges" },
    { key: "disabled-field-labels", title: "Disabled field labels" },
  ],
  "ui/separator/page": [
    { key: "default", title: "Default" },
    { key: "solid-line", title: "Solid line" },
    { key: "dotted-line", title: "Dotted line" },
    { key: "light-weight", title: "Light weight" },
    { key: "bold-weight", title: "Bold weight" },
    { key: "brand-rule", title: "Brand rule" },
    { key: "dark-dividers", title: "Dark dividers" },
    { key: "tight-column", title: "Tight column" },
    { key: "explicit-gap", title: "Explicit gap" },
    { key: "before-a-heading", title: "Before a heading" },
    { key: "outside-a-prose-column", title: "Outside a prose column" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
  ],
  "ui/table/page": [
    { key: "declarative-rows", title: "Declarative rows" },
    { key: "composed-parts", title: "Composed parts" },
    { key: "elements-as-cell-content", title: "Elements as cell content" },
    { key: "inputs-in-cells", title: "Inputs in cells" },
    {
      key: "outer-border-with-row-lines",
      title: "Outer border with row lines",
    },
    { key: "brand-grid-lines", title: "Brand grid lines" },
    { key: "grid-edge-override", title: "Grid edge override" },
    { key: "cell-edge-override", title: "Cell edge override" },
    { key: "row-edge-override", title: "Row edge override" },
    { key: "caption-options", title: "Caption options" },
    { key: "header-control-sizes", title: "Header control sizes" },
    { key: "nested-table-edges", title: "Nested table edges" },
    { key: "colored-cell-layers", title: "Colored cell layers" },
    { key: "row-lines-only", title: "Row lines only" },
    { key: "outer-border-only", title: "Outer border only" },
    { key: "inset-column-dividers", title: "Inset column dividers" },
    { key: "brand-head", title: "Brand head" },
    { key: "sticky-head-and-foot", title: "Sticky head and foot" },
    { key: "pinned-first-column", title: "Pinned first column" },
    { key: "pinned-end-column", title: "Pinned end column" },
    { key: "right-to-left", title: "Right to left" },
    { key: "sortable-headers", title: "Sortable headers" },
    { key: "descending-numeric-sort", title: "Descending numeric sort" },
    { key: "selected-rows", title: "Selected rows" },
    { key: "focusable-rows", title: "Focusable rows" },
    { key: "compact-density", title: "Compact density" },
    { key: "wide-side-padding", title: "Wide side padding" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
    { key: "table-cell-layer", title: "Table cell layer" },
    { key: "table-rows", title: "Table rows" },
    { key: "mixed-row-keys", title: "Mixed row keys" },
    { key: "element-cell-values", title: "Element cell values" },
  ],
  "ui/tabs/page": [
    { key: "default", title: "Default" },
    { key: "shared-panel", title: "Shared panel" },
    { key: "without-padding", title: "Without padding" },
    {
      key: "without-padding-or-root-edge",
      title: "Without padding or root edge",
    },
    { key: "full-width-strip", title: "Full-width strip" },
    { key: "edgeless", title: "Edgeless" },
    { key: "hidden-root-edge", title: "Hidden root edge" },
    { key: "thick-edge", title: "Thick edge" },
    { key: "brand-edge", title: "Brand edge" },
    { key: "bold-edge", title: "Bold edge" },
    { key: "square-panel-corners", title: "Square panel corners" },
    { key: "flat-tabs", title: "Flat tabs" },
    { key: "bevel-tabs", title: "Bevel tabs" },
    { key: "folder-glider", title: "Folder glider" },
    { key: "flat-glider", title: "Flat glider" },
    { key: "bevel-glider", title: "Bevel glider" },
    { key: "borderless-flat-glider", title: "Borderless flat glider" },
    { key: "borderless-bevel-glider", title: "Borderless bevel glider" },
    { key: "bar-glider", title: "Bar glider" },
    { key: "small-tabs", title: "Small tabs" },
    { key: "tabs-with-icons", title: "Tabs with icons" },
    { key: "tab-with-a-badge", title: "Tab with a badge" },
    { key: "disabled-tab", title: "Disabled tab" },
    { key: "chevron-separators", title: "Chevron separators" },
    { key: "pipe-separators", title: "Pipe separators" },
    { key: "right-to-left", title: "Right to left" },
    { key: "overflowing-strip", title: "Overflowing strip" },
    { key: "on-a-brand-layer", title: "On a brand layer" },
    { key: "tab-panel-shared-store", title: "Tab panel shared store" },
    { key: "tabs-record", title: "Tabs record" },
    {
      key: "folder-tab-with-a-long-label",
      title: "folder tab with a long label",
    },
    { key: "flat-tab-with-a-long-label", title: "flat tab with a long label" },
    {
      key: "bevel-tab-with-a-long-label",
      title: "bevel tab with a long label",
    },
    { key: "bar-placement", title: "Bar placement" },
  ],
  "ui/text-frame/page": [
    { key: "section-label", title: "Section label" },
    { key: "side-padding-steps", title: "Side padding steps" },
  ],
  "ui/tooltip/page": [
    { key: "default", title: "Default" },
    { key: "with-an-arrow", title: "With an arrow" },
    { key: "placed-below", title: "Placed below" },
    { key: "long-label", title: "Long label" },
    {
      key: "icon-button-with-a-shortcut",
      title: "Icon button with a shortcut",
    },
    { key: "pill", title: "Pill" },
    { key: "roomy-padding", title: "Roomy padding" },
    { key: "brand", title: "Brand" },
    { key: "inverted", title: "Inverted" },
    { key: "hover-or-focus", title: "Hover or focus" },
  ],
  "ui/list/keeps-marker-shapes-and-guides-in-forced-colors":
    listCaptureSections,
};

/** Resolves the complete declared section set without deriving identities. */
export async function getCaptureSections(
  main: Locator,
  sections: readonly CaptureSection[],
) {
  const articles = main.locator(":scope > article");
  if ((await articles.count()) !== sections.length) {
    throw new Error(
      "Ariviso page sections changed; update the explicit capture declarations",
    );
  }
  const keys = new Set<string>();
  const titles = new Set<string>();
  const captures = [];
  for (const section of sections) {
    if (keys.has(section.key) || titles.has(section.title)) {
      throw new Error(
        "Ariviso page sections require unique explicit keys and titles",
      );
    }
    keys.add(section.key);
    titles.add(section.title);
    const element = main
      .getByRole("article", { name: section.title, exact: true })
      .and(articles);
    if ((await element.count()) !== 1) {
      throw new Error(
        `Ariviso page section is missing or ambiguous: ${section.title}`,
      );
    }
    captures.push({ key: section.key, element });
  }
  return captures;
}
