name: apply-generated-patch

on:
  workflow_run:
    workflows: ["og-images", "build-styles"]
    types:
      - completed

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update PR
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_repository.full_name != github.repository
    steps:
      - name: Create artifact temp directory
        run: mkdir -p "${{ runner.temp }}/artifacts"

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ runner.temp }}/artifacts

      - name: Determine patch file
        id: patch
        env:
          ARTIFACTS_DIR: ${{ runner.temp }}/artifacts
        run: node --experimental-strip-types .github/scripts/apply-generated-patch.ts determine-patch-file

      - name: Checkout trusted repository
        if: steps.patch.outputs.file
        uses: actions/checkout@v6

      - name: Checkout PR
        if: steps.patch.outputs.file
        uses: actions/checkout@v6
        with:
          path: pr
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          token: ${{ secrets.ARIAKIT_BOT_PAT }}

      - name: Apply patch
        if: steps.patch.outputs.file
        env:
          PATCH_FILE: ${{ steps.patch.outputs.file }}
          WORKING_DIRECTORY: pr
        run: node --experimental-strip-types .github/scripts/apply-generated-patch.ts apply-patch

      - name: Commit changes
        if: steps.patch.outputs.file
        uses: ./.github/workflows/commit-or-pr
        with:
          working-directory: pr
          event: pull_request
          message: ${{ steps.patch.outputs.message }}
          head-branch: ${{ github.event.workflow_run.head_branch }}
          new-branch: ignore
          token: ${{ secrets.ARIAKIT_BOT_PAT }}
