name: deploy

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: Deploy to production
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: blacksmith-4vcpu-ubuntu-2404
    environment: Production
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up environment
        uses: ./.github/workflows/setup

      - name: Build app
        run: pnpm run build-app

      - name: Deploy Next.js app to Cloudflare
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: nextjs
          command: deploy

      - name: Deploy app to Cloudflare
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: app
          command: deploy
