name: e2e

on:
  issue_comment:
    types: [created, edited]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo debug(github.event)

  # install:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Set up Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version-file: .nvmrc

  #     - name: Cache node_modules
  #       uses: actions/cache@v3
  #       id: cache-node-modules
  #       with:
  #         path: |
  #           node_modules
  #           packages/*/node_modules
  #         key: npm-${{ hashFiles('package-lock.json') }}

  #     - name: Install dependencies
  #       if: steps.cache-node-modules.outputs.cache-hit != 'true'
  #       run: npm ci --no-audit --ignore-scripts

  # test:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Set up Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version-file: .nvmrc

  #     - name: Cache node_modules
  #       uses: actions/cache@v3
  #       id: cache-node-modules
  #       with:
  #         path: |
  #           node_modules
  #           packages/*/node_modules
  #         key: npm-${{ hashFiles('package-lock.json') }}

  #     - name: Install dependencies
  #       if: steps.cache-node-modules.outputs.cache-hit != 'true'
  #       run: npm ci --no-audit --ignore-scripts

  #     - name: Get number of CPU cores
  #       uses: SimenB/github-actions-cpu-cores@v1
  #       id: cpu-cores

  #     - name: Test
  #       run: >
  #         npm test-e2e --
  #         --max-workers ${{ steps.cpu-cores.outputs.count }}
