name: e2e
on:
  deployment_status:
    types: [success]

jobs:
  test:
    # if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Echo
        run: echo ${{ github.event.deployment_status.target_url }}
