name: install-node-modules-linux

on:
  workflow_call:
    outputs:
      npm-cache-path:
        description: Path to cache npm
        value: ${{ jobs.install.outputs.npm-cache-path }}
      npm-cache-key:
        description: Key to cache npm
        value: ${{ jobs.install.outputs.npm-cache-key }}
      node-modules-cache-path:
        description: Path to cache node modules
        value: ${{ jobs.install.outputs.node-modules-cache-path }}
      node-modules-cache-key:
        description: Key to cache node modules
        value: ${{ jobs.install.outputs.node-modules-cache-key }}

jobs:
  install:
    name: Install node modules (macOS)
    runs-on: macos-latest
    outputs:
      npm-cache-path: ${{ steps.install.outputs.npm-cache-path }}
      npm-cache-key: ${{ steps.install.outputs.npm-cache-key }}
      node-modules-cache-path: ${{ steps.install.outputs.node-modules-cache-path }}
      node-modules-cache-key: ${{ steps.install.outputs.node-modules-cache-key }}

    steps:
      - name: Install node modules
        id: install
        uses: ./.github/actions/install-node-modules.yml
