name: og-images

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    name: Generate OG images
    runs-on: macos-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install node modules
        uses: ./.github/workflows/install-node-modules

      - name: Install Playwright
        uses: ./.github/workflows/install-playwright
        with:
          engine: chromium

      - name: Run app dev server
        run: node --experimental-strip-types .github/scripts/og-images.ts run-dev-server

      - name: Generate OG images
        run: npm run og-image-generate -w site

      - name: Generate patch or commit
        uses: ./.github/workflows/patch-or-commit
        with:
          message: Update OG images
          new-branch: chore/update-og-images
          patch-file: og-images.patch
          patch-name: og-images-diff
          token: ${{ secrets.ARIAKIT_BOT_PAT }}
