name: preview-deploy

on:
  workflow_run:
    workflows: ["app"]
    types: [completed]

jobs:
  deploy-preview:
    name: Deploy preview
    runs-on: ubuntu-latest
    environment: Preview
    concurrency:
      group: deploy-preview-${{ github.event.workflow_run.head_branch }}
    permissions:
      actions: read
      contents: read
      deployments: write
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check repository
        id: check-repo
        run: |
          if [ "${{ github.event.workflow_run.head_repository.full_name }}" = "${{ github.repository }}" ]; then
            echo "same_repo=true" >> "$GITHUB_OUTPUT"
          else
            echo "same_repo=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set commit status (pending)
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const args = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.workflow_run.head_sha }}',
              state: 'pending',
              target_url: runUrl,
            };
            await github.rest.repos.createCommitStatus({ ...args, context: 'Preview (commit)' });
            if ('${{ steps.check-repo.outputs.same_repo }}' === 'true') {
              await github.rest.repos.createCommitStatus({ ...args, context: 'Preview (branch)' });
            }

      - name: Generate preview alias
        id: alias
        if: steps.check-repo.outputs.same_repo == 'true' && github.event.workflow_run.head_branch != 'main'
        env:
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          SAFE=$(printf "%s" "$HEAD_BRANCH" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9-]+#-#g' | sed -E 's#^-+##; s#-+$##')
          echo "slug=$SAFE" >> "$GITHUB_OUTPUT"

      - name: Cache node_modules
        uses: actions/cache/restore@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            site/node_modules
            packages/*/node_modules
          key: node-modules-${{ hashFiles('package-lock.json', '.nvmrc') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit

      - name: Download app artifact
        uses: actions/download-artifact@v5
        with:
          name: app-dist
          path: site/dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload app version
        id: versions
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: >-
            versions upload --env preview
            ${{ steps.alias.outputs.slug && format('--preview-alias {0}', steps.alias.outputs.slug) }}

      - name: Deploy app version
        if: steps.check-repo.outputs.same_repo == 'true' && github.event.workflow_run.head_branch == 'main'
        id: deploy
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: deploy --env preview

      - name: Set commit status (result)
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const versionsOutcome = '${{ steps.versions.outcome }}';
            const deployOutcome = '${{ steps.deploy.outcome }}';
            const deployUrl = '${{ steps.deploy.outputs.deployment-url }}';
            const versionUrl = '${{ steps.versions.outputs.deployment-url }}';
            const aliasUrl = '${{ steps.alias.outputs.slug }}' && versionUrl
              ? versionUrl.replace(/^(https?:\/\/)[^-]+/, `$1${{ steps.alias.outputs.slug }}`)
              : '';
            const commitTarget = (versionsOutcome === 'success' && versionUrl)
              ? versionUrl
              : '';
            const branchTarget = (versionsOutcome === 'success' && aliasUrl)
              ? aliasUrl
              : (deployOutcome === 'success' && deployUrl) ? deployUrl : '';
            const args = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.workflow_run.head_sha }}',
            };
            await github.rest.repos.createCommitStatus({
              ...args,
              state: commitTarget ? 'success' : 'failure',
              target_url: commitTarget || runUrl,
              context: 'Preview (commit)',
            });
            if ('${{ steps.check-repo.outputs.same_repo }}' === 'true') {
              await github.rest.repos.createCommitStatus({
                ...args,
                state: branchTarget ? 'success' : 'failure',
                target_url: branchTarget || runUrl,
                context: 'Preview (branch)',
              });
            }
