name: preview-deploy

on:
  workflow_run:
    workflows: ["main"]
    types: [completed]

jobs:
  deploy-preview-version:
    name: Deploy preview version
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      deployments: write
    environment: preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: site/dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload app version
        id: upload
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: versions upload --env preview

  deploy-preview:
    name: Deploy preview
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-preview-${{ github.event.workflow_run.head_branch }}
      cancel-in-progress: true
    permissions:
      actions: read
      contents: read
      deployments: write
    environment: preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: site/dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: deploy --env preview
