name: release-preview

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Install node modules
        uses: ./.github/workflows/install-node-modules
        with:
          cache-npm: true

      - name: Build
        run: npm run build

      - name: Get changeset status
        id: changeset-status
        env:
          BASE_REF: ${{ github.base_ref }}
        run: node --experimental-strip-types .github/scripts/release-preview.ts get-changeset-status

      - name: Compute affected packages
        id: compute-affected-packages
        if: steps.changeset-status.outputs.has-changesets == 'true'
        run: node --experimental-strip-types .github/scripts/release-preview.ts compute-affected-packages

      - name: Publish preview
        if: steps.changeset-status.outputs.has-changesets == 'true'
        env:
          AFFECTED_PACKAGES: ${{ steps.compute-affected-packages.outputs.affected-packages }}
        run: node --experimental-strip-types .github/scripts/release-preview.ts publish-preview
