name: Update screenshots

on:
  workflow_run:
    workflows: ["app"]
    types: [completed]
  workflow_dispatch:
    inputs:
      run_id:
        description: app workflow run ID
        required: true
      head_repo:
        description: head repository (owner/repo)
        required: true
      head_ref:
        description: head branch
        required: true

jobs:
  update-screenshots:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (
        github.event.workflow_run.conclusion != 'skipped' &&
        github.event.workflow_run.conclusion != 'cancelled' &&
        (github.event.workflow_run.event == 'pull_request' || github.event.workflow_run.event == 'push')
      )
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          repository: ${{ github.event_name == 'workflow_dispatch' && inputs.head_repo || github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.head_ref || github.event.workflow_run.head_branch }}
          token: ${{ secrets.ARIAKIT_BOT_PAT }}
          persist-credentials: true

      - name: Download screenshots artifacts
        uses: actions/download-artifact@v5
        with:
          run-id: ${{ github.event_name == 'workflow_dispatch' && inputs.run_id || github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: app-screenshots-*
          merge-multiple: true
          path: site/src/tests/screenshots

      - name: Configure git
        run: |
          git config user.name "ariakit-bot"
          git config user.email "ariakit-bot@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add -A site/src/tests/screenshots
          if git diff --cached --quiet --exit-code; then
            echo "No screenshots to commit."
            exit 0
          fi
          git commit -m "Update screenshots"

      - name: Push to PR head branch
        if: github.event.workflow_run.event == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.head_ref != 'main')
        run: |
          set +e
          HEAD_REF='${{ github.event_name == 'workflow_dispatch' && inputs.head_ref || github.event.workflow_run.head_branch }}'
          git push origin HEAD:"${HEAD_REF}"
          status=$?
          if [ $status -ne 0 ]; then
            echo "Failed to push to PR head."
            exit 1
          fi

      - name: Create PR with screenshots
        if: github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update screenshots
          title: Update screenshots
          branch: chore/update-screenshots
          delete-branch: true
          base: ${{ github.event.workflow_run.head_branch }}
          token: ${{ secrets.ARIAKIT_BOT_PAT }}
          add-paths: |
            site/src/tests/screenshots/**
