name: update-screenshots

on:
  workflow_run:
    workflows: ["app"]
    types: [completed]

concurrency:
  group: update-screenshots-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  gate:
    runs-on: ubuntu-latest
    outputs:
      is_latest: ${{ steps.check.outputs.is_latest }}
    steps:
      - name: Read tip SHA on the branch
        id: tip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REPO: ${{ github.event.workflow_run.head_repository.full_name }}
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          set -euo pipefail
          # Get current tip commit of the branch in the head repo
          tip_sha=$(gh api repos/$HEAD_REPO/commits/$HEAD_BRANCH --jq .sha)
          echo "tip_sha=$tip_sha" >> "$GITHUB_OUTPUT"

      - name: Compare with triggering run SHA
        id: check
        run: |
          if [ "${{ github.event.workflow_run.head_sha }}" = "${{ steps.tip.outputs.tip_sha }}" ]; then
            echo "is_latest=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_latest=false" >> "$GITHUB_OUTPUT"
          fi

  update-screenshots:
    name: Update screenshots
    needs: gate
    if: needs.gate.outputs.is_latest == 'true'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          token: ${{ secrets.ARIAKIT_BOT_PAT }}
          persist-credentials: true

      - name: Download screenshots artifacts
        uses: actions/download-artifact@v5
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: app-screenshots-*
          merge-multiple: true
          path: site/src/tests/screenshots

      - name: Configure git
        run: |
          git config user.name "ariakit-bot"
          git config user.email "ariakit-bot@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add -A site/src/tests/screenshots
          if git diff --cached --quiet --exit-code; then
            echo "No screenshots to commit."
            exit 0
          fi
          git commit -m "Update screenshots"

      - name: Push to PR head branch
        if: github.event.workflow_run.event == 'pull_request'
        run: |
          set +e
          HEAD_REF='${{ github.event.workflow_run.head_branch }}'
          git push origin HEAD:"${HEAD_REF}"
          status=$?
          if [ $status -ne 0 ]; then
            echo "Failed to push to PR head."
            exit 1
          fi

      - name: Create PR with screenshots
        if: github.event.workflow_run.event == 'push'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update screenshots
          title: Update screenshots
          branch: chore/update-screenshots
          delete-branch: true
          base: ${{ github.event.workflow_run.head_branch }}
          token: ${{ secrets.ARIAKIT_BOT_PAT }}
          add-paths: |
            site/src/tests/screenshots/**
